### ISSUE TITLE
If fstype is not filled in StorageClass, the value of fstype will be set to ext4 by default, and hwameistor does not support ext4 for the time being

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1001]
If fstype is not filled in StorageClass, the value of fstype will be set to ext4 by default, and hwameistor does not support ext4 for the time being

**Comment by zhaosimon** [comment]
current StorageClasses are created by operator?  Is there a way to specify 'fstype'?

**Comment by SSmallMonster** [comment]
DUP: #1020 

planed in August.
