### ISSUE TITLE
The totalVolumeCount field of LocalStorageNode needs to be able to be customized by the user

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1003]
The totalVolumeCount field of LocalStorageNode needs to be able to be customized by the user

**Comment by zhaosimon** [comment]
<img width="398" alt="image" src="https://github.com/hwameistor/hwameistor/assets/36882380/9ec76c95-ec9a-45f8-93f1-cdcaa089d234">

The current number 1000 does not make sense?  should we clarify: 1. what is the reasonable number for this.   2. who can define this number?

**Comment by SSmallMonster** [comment]
planed in November.
