### ISSUE TITLE
node is healthy, pod is running , but lsn status is offline

### ISSUE THREAD

**Issue by liyuerich** [hwameistor/hwameistor#1012]
1 check nodes status, both are healthy

<img width="756" alt="image" src="https://github.com/hwameistor/hwameistor/assets/97269208/38af9674-5c10-4e86-9074-ecb15957473c">

2 check lsn and find one node lsn status is offline 

<img width="723" alt="image" src="https://github.com/hwameistor/hwameistor/assets/97269208/46aa29ff-8876-4f76-ae6c-e8f939bf5764">

3 check logs, it seems lost cpnnection

<img width="1139" alt="企业微信截图_e438aa22-7902-4be2-8b1b-178bd37d589e" src="https://github.com/hwameistor/hwameistor/assets/97269208/1588f322-f42e-4437-b6ca-78881392d742">

**Comment by FloatXD** [comment]
Need to sync timezone

**Comment by FloatXD** [comment]
The status is normal after synchronizing the time zone

**Comment by liyuerich** [comment]
thanks your quick response
