### ISSUE TITLE
Installing hwameistor via hwameistor-operator, DRBD is not installed automatically?

### ISSUE THREAD

**Issue by ty-dc** [hwameistor/hwameistor#1014]
Output of `kubectl version`:
```
~# kubectl version --short
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.4
```

**Executing drbdadm status was unsuccessful**
```
[root@controller-node-1 ~]# drdbadm status
-bash: drdbadm: command not found
[root@controller-node-1 ~]# drdbadm status
-bash: drdbadm: command not found
```

**system version**
```
[root@controller-node-1 ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

**Comment by zhaosimon** [comment]
DRBD is optional for HA, need to install on demand

**Comment by zhaosimon** [comment]
<img width="722" alt="屏幕快照 2023-07-28 上午10 47 52" src="https://github.com/hwameistor/hwameistor/assets/36882380/aeff39b7-940b-4dfb-99a2-7b538bd9a50f">

please try to verify with this

**Comment by buffalo1024** [comment]
Can you show node.status.nodeInfo.osImage?

**Comment by zhaosimon** [comment]
kubectl node.status.nodeInfo.osImage
