### ISSUE TITLE
can Component of Hwameistor  be chosen to install ?

### ISSUE THREAD

**Issue by qiupingdai** [hwameistor/hwameistor#1019]
the HA function is not neccesary for our scenario ,  can the following components be chosen not to install?
1. ui、apiserver for web dashboard 
2. exporter for metrics
3. volume-evitor for HA &Migration

and only install the following components :
1. local-disk-manager
2. local-storage
3. local-storage-csi-controller 4. local-disk-csi-controller
5. operator
6. admission-controller
    
7. scheduler

**Comment by qiupingdai** [comment]
yes ，we will export the switch to disable this component when install hwameistor by operator

**Comment by sun7927** [comment]
is it a customer's requirement? or requirement from the product?

**Comment by buffalo1024** [comment]
done
