### ISSUE TITLE
 hwameistor ui cannot display nvme disks 

### ISSUE THREAD

**Issue by lcy0108** [hwameistor/hwameistor#1031]
hwameistor ui cannot display nvme disks 
hwameistor ui 
![image](https://github.com/hwameistor/hwameistor/assets/41486737/6fa3afbc-77eb-4fac-a0c4-97a39331d92a)

lsblk
![image](https://github.com/hwameistor/hwameistor/assets/41486737/d497a52b-36de-430f-80ee-53afa5f1d853)

web Console /cluster/pools/:poolName/nodes/:nodeName/disks
![image](https://github.com/hwameistor/hwameistor/assets/41486737/65c59fcc-dc6c-424b-998b-26f6530b42c5)

when I request the api  the pod apiserver logs

 
![image](https://github.com/hwameistor/hwameistor/assets/41486737/3824316e-6b80-4d5e-b792-322fdd740918)

**Comment by sun7927** [comment]
currently, the HwameiStor still has a problem to detect NVMe disk type correctly. Will fix it soon

check https://github.com/hwameistor/hwameistor/issues/989

**Comment by buffalo1024** [comment]
it's a bug of hwameistor-apiserver, i will fix it later.
