### ISSUE TITLE
After the node is down and restored, the pod that use hwameistor is pending

### ISSUE THREAD

**Issue by Penguin-zlh** [hwameistor/hwameistor#1082]
After the node is down and restored, the pod that use hwameistor is pending:

<img width="462" alt="image" src="https://github.com/hwameistor/hwameistor/assets/57695165/307692f5-ce07-47ce-8f5f-eeec7416f45a">

**Comment by SSmallMonster** [comment]
the root cause is the missing of symbol link to logic volume under /dev/LocalStorage_PoolHDD.

is there any system log about this logic volume or lvm?

**Comment by Penguin-zlh** [comment]
whether this can help

![image](https://github.com/hwameistor/hwameistor/assets/57695165/5baefc30-07f0-46d4-8cfa-805e425d789e)


> the root cause is the missing of symbol link to logic volume under /dev/LocalStorage_PoolHDD.
> 
> is there any system log about this logic volume or lvm?

**Comment by SSmallMonster** [comment]
sadly, it seems no key log shown in the screenshots.

**Comment by zhaosimon** [comment]
Close with solution
