### ISSUE TITLE
`listDisksOwnedByLocalStorage` use stale info

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#1086]
pkg/local-disk-manager/controller/localdisk/localdisk_controller.go:

```go
func listDisksOwnedByLocalStorage(cli client.Client, nodeName string) ([]string, error) {
	lsn := v1alpha1.LocalStorageNode{}
	// FIXME If lsn has not already rebuilt completely after restarting, stale data will be obtained here
	// Waiting localRegistry rebuild completely and using localRegistry directly is a good solution like listDisksOwnedByLocalDiskManager.
	err := cli.Get(context.Background(), types.NamespacedName{Name: nodeName}, &lsn)
	if err != nil {
		if errors.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}

	// list all devices existed in storage pool
	var poolDisks []string
	for _, pool := range lsn.Status.Pools {
		for _, disk := range pool.Disks {
			poolDisks = append(poolDisks, disk.DevPath)
		}
	}

	return poolDisks, nil
}

```

**Comment by SSmallMonster** [comment]
one way to prevent this is wait `LocalStorageNode` cache completely synced, another way is using info on the host like `lvm` to find if disks assigned to `LocalStorage`.

The only effect of the second approach is that it introduces a dependency on LVM.

**Comment by AmazingPangWei** [comment]
Yes, both methods are reasonable. But for the first method, how to wait `LocalStorageNode` cache completely synced?

**Comment by SSmallMonster** [comment]
> Yes, both methods are reasonable. But for the first method, how to wait `LocalStorageNode` cache completely synced?

I think it is difficult to ensure that the resources of the server are completely synchronized. One way is to listen to the changes of LSN resources to trigger LD tuning, but I prefer the second approach.

**Comment by AmazingPangWei** [comment]
I agree with you.

**Comment by SSmallMonster** [comment]
fixed at https://github.com/hwameistor/hwameistor/pull/1088
