### ISSUE TITLE
hwameistor-pvc-autoresizer failed to run

### ISSUE THREAD

**Issue by qilongqiu** [hwameistor/hwameistor#1122]
See the null pointer problem from the log
<img width="1229" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/df1cea2e-c579-4ad5-a35d-039239ff7a71">
Check the source code from the stack, it should be to query pvc or the like
<img width="765" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/4da1c569-29a0-4fda-99ac-3c1da5328897">

There is manually managed pv/pvc in my cluster, which has no corresponding sc
<img width="884" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/8f0c21ec-96b0-4b55-9a44-9a785282cea8">
After deleting these pv/pvc, it can start normally
<img width="687" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/20d2629d-76a8-433e-85cf-35657c4021d1">
<img width="1235" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/94e022db-446c-4610-b228-1fbb4c711f59">

I think this should be a bug

**Comment by buffalo1024** [comment]
thank you.i will have a look at it.
