### ISSUE TITLE
Cannot specify localdisk `diskAttributes.type`

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#1130]
Sometimes, localdisk `diskAttributes.type` detected by hwameistor is not correct. Localdisk `diskAttributes.type` will be changed back if I modify it and restart ldm pod.

We should come up with a solution to cover this issue.

**Comment by SSmallMonster** [comment]
releated issue: https://github.com/hwameistor/hwameistor/issues/313

**Comment by SSmallMonster** [comment]
this #1138 is a workaround for fix wrong diskType detected for now.

example: modify diskType as **SSD**
```shell
$ kubectl patch ld  --type='merge'  <localdisk_name> -p '{"spec":{"diskAttributes": {"type": "SSD"}}}'
```
