### ISSUE TITLE
The issue of incorrect judgment of disk type

### ISSUE THREAD

**Issue by cqmmm** [hwameistor/hwameistor#1137]
Based on the previous issue, I understand that `hwameistor` determines the type of disk by examining the contents of `/sys/block/*/queue/rotational`. If it's 1, it's determined as an `HDD`, and if it's 0, it's determined as an `SSD`.

the nodes are returning 1, so `hwameistor` will classify them as HDDs.
<img width="450" alt="image" src="https://github.com/hwameistor/hwameistor/assets/74850217/a52c8c17-9959-4b2a-86ce-6770c57c198c">
ld:
<img width="435" alt="image" src="https://github.com/hwameistor/hwameistor/assets/74850217/911c8678-93a1-459d-85b6-1a5b8f555f4f">
lsn:
<img width="488" alt="image" src="https://github.com/hwameistor/hwameistor/assets/74850217/c0fd93e2-96e5-4a55-95c1-192e01097714">

But in VMware, we can see that the disk type is `SSD`. In this issue, how can `hwameistor` correctly recognize the disk type?
![wecom-temp-165225-ae7d8cda1e77e27c936217a9ea7308a5](https://github.com/hwameistor/hwameistor/assets/74850217/9f944d45-150a-4461-85c9-727dccbe6f83)

**Comment by SSmallMonster** [comment]
as you mentioned above, hwameistor  determines the type of disk by examining the contents of /sys/block/*/queue/rotational.

If the rotational file on the host is wrong, then the result we recognize is also wrong.

**Comment by SSmallMonster** [comment]
see #1138 for manually workaround.

**Comment by sun7927** [comment]
what caused the the rotational value wrong?

**Comment by FloatXD** [comment]
![企业微信截图_16969254808916](https://github.com/hwameistor/hwameistor/assets/76234281/7f52f653-12b3-4ccd-8582-2fabb9fd8729)
Need to confirm this part of the configuration

**Comment by cqmmm** [comment]
Drive type is flash
![Uploading image.png…]()

**Comment by SSmallMonster** [comment]
can you show ` lsblk -o +ROTA` output?

our mechanism for identifying the type of disk is the same as lsblk. If the output of `ROTA` is 1, it means that it is an HDD disk. I'd like to confirm that if this is the expected result.
