### ISSUE TITLE
make snapshot feature configurable

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#1147]
In some cases, users like me don't need snapshot feature. Making it configurable will be good.

**Comment by SSmallMonster** [comment]
cc @buffalo1024

**Comment by sun7927** [comment]
> In some cases, users like me don't need snapshot feature. Making it configurable will be good.

snapshot will be shipped with the main functions, will be triggered by following CSI. If user doesn't want it, it's okay not to trigger it. it should be okay.

**Comment by liyang516** [comment]
> > In some cases, users like me don't need snapshot feature. Making it configurable will be good.
> 
> snapshot will be shipped with the main functions, will be triggered by following CSI. If user doesn't want it, it's okay not to trigger it. it should be okay.

Support in 0.13.0 helmchart?

**Comment by buffalo1024** [comment]
supported
