### ISSUE TITLE
Why are replicas schedule to other nodes when deployment replicas > 1 ?

### ISSUE THREAD

**Issue by qilongqiu** [hwameistor/hwameistor#1155]
Now my Pods are on the same node
<img width="1154" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/8f436479-eb5a-4ff2-ba0b-1430f97073b1">

The default scheduler is used, and hwameistor
<img width="1064" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/6d65a30a-442b-4c7e-813c-41948237f68e">

When I delete the pod, the new pod is schedule to other nodes
<img width="1277" alt="企业微信截图_63ad012d-4200-459f-8b79-3c5f0862e48c" src="https://github.com/hwameistor/hwameistor/assets/19998264/54d3455a-7e93-4d71-8d4e-e66cb5d9fe14">

From the pod details, it looks like hwameistor-scheduler should be performing the scheduling

<img width="1439" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/23f1d50f-d866-4f7f-b7bb-0bf5d64dd549">

Looking at pvc and lv, it's primary on node xx-sapva-dcm1
<img width="1061" alt="企业微信截图_870a44ee-acd6-4e69-bd58-07923e0aa032" src="https://github.com/hwameistor/hwameistor/assets/19998264/207c9177-5bd2-449a-af7d-cf711d742123">

Should it automatically schedule the new pod to the node where the primary lvr is located?

**Comment by SSmallMonster** [comment]
This field has no meaning for the user and will only be used during the initialization and update configuration stages.

During the scheduling period, the nodes where all replicas with a `Ready` state are located can be used as the master node, which is different from the Primary node mentioned by the application layer(e.g. mysql). In the case of consistent data, the master node can completely drift.

**Comment by qilongqiu** [comment]
I don't think this is right, hwameistor should do this scheduling function

The drdb state of lvr is master-slave related
<img width="588" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/54fcb97c-a30d-47f1-8755-d532e6d8f170">
<img width="633" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19998264/f0838fef-89e5-4b46-b5eb-998a0bcb53c3">

**Comment by SSmallMonster** [comment]
DRBD status is changed to Primary/Secondary after scheduling, when no workload is using this volume, the DRBD volume status also changed to Secondary/Secondary.

So, DRBD status is changing after scheduling rather scheduling acording to DRBD status.

**Comment by SSmallMonster** [comment]
After research, the scheduler may select a node which is Secondary when workload's replica >= 2. 

This is a bug, the correct schedule result should be the same node which first scheduled.
