### ISSUE TITLE
An error will occur if two restores are issued to a snapshot at the same time.

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1192]
![企业微信截图_16980533759128](https://github.com/hwameistor/hwameistor/assets/76234281/6fec6df2-56cd-4479-8604-3c4fecb38b49)

**Comment by SSmallMonster** [comment]
i think the issue happens at:
https://github.com/hwameistor/hwameistor/blob/d0ed7e269efd39ab2c07cb61acc8a55a343a9d78/pkg/local-storage/member/controller/volume_snapshot_restore_task_worker.go#L350-L355

`task name of snapshotRestore` also need considerd to filter
