### ISSUE TITLE
more events is needed when assign disk for localdiskclaim

### ISSUE THREAD

**Issue by dchjingyue** [hwameistor/hwameistor#1218]
Output of `lsblk`:
```
#  lsblk
```
![image](https://github.com/hwameistor/hwameistor/assets/86140231/ca6a55f1-5a5f-435a-9879-a7e7b217f6a6)
Output of `blkid`:
```
# blkid

```
![image](https://github.com/hwameistor/hwameistor/assets/86140231/297ce539-139d-471d-bd44-3fc41952ec22)
Output of `kubectl version`:
```
# paste output here  DCE5 0.8.0
```
when localdiskclaim is failure, users should oberve error logs or events from localdiskclaim object rather search logs in pods

**Comment by SSmallMonster** [comment]
@hikariwo can you have a look?

**Comment by hikariwo** [comment]
A feature is needed about adding `message` field to `ldc` to record the `ldc` current running error message. The `ldc` object and the log both record the state machine error log.

**Comment by SSmallMonster** [comment]
> A feature is needed about adding `message` field to `ldc` to record the `ldc` current running error message. The `ldc` object and the log both record the state machine error log.

Yes.
