### ISSUE TITLE
"Improve Readability of CAPACITY and USED Data Units in 'kubectl get lv' Output"

### ISSUE THREAD

**Issue by wwwnay** [hwameistor/hwameistor#1219]
The units displayed for CAPACITY and USED data obtained from `kubectl get lv` lack readability. 
The units shown in `kubectl get pvc` are all in Gi.
```
[root@g-master1 ~]# kubectl get localvolumes
pvc-00e450f6-d98c-4216-ba34-85c3d9a04807   LocalStorage_PoolHDD   1          16106127360    398192640     Ready   -1         g-master2   xfs      41d
pvc-09aa703c-c62e-4b55-9832-98a6d159e62f   LocalStorage_PoolHDD   1          1073741824     42676224      Ready   -1         g-master2   xfs      41d
```

**Comment by SSmallMonster** [comment]
@wwwnay thanks for your feedback.

Yes, from a user perspective, G/M may be more user-friendly, perhaps we should convert this when outputting.

**Comment by hikariwo** [comment]
IMO, adding the display capacity field to the resources which need to display capacity. And the capacity units can define by resources annotation for user's favour.

**Comment by sun7927** [comment]
suggest to fully use hwameictl to manage the hwameistor system instead of kubectl, and also help to enhance hwameictl tool.
