### ISSUE TITLE
Pod FailedScheduling with volumesnapshot pvc while it's original pvc deleted

### ISSUE THREAD

**Issue by liyang516** [hwameistor/hwameistor#1240]
**Environment**
KubeVirt version: v1.0.0
Cdi version:  v1.57.0
Kubernetes version: v1.28.2
Hwameistor version: v0.13.0
Storage class: hwameistor-lvm-hdd

**How to reproduce it**

1. Create a pvc with hwameistor-storage-lvm-hdd(sc)  named source-pvc
```shell
# cat source-pvc.yml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: hwameistor-storage-lvm-hdd
```  

2. Create a pod use source-pvc， named nginx1
```shell
# cat nginx1.yml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: default
spec:
  containers:
  - name: nginx
    image: ecr-sh.yun.qianxin-inc.cn/alkaid/nginx:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: data
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: source-pvc
``` 

3. Create a volumespapshot for source-pvc, named source-pvc-snapshot
```shell
# cat pvc-snap.yml 
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: source-pvc-snapshot
spec:
  volumeSnapshotClassName: hwameistor-storage-lvm-snapshot
  source:
    persistentVolumeClaimName: source-pvc
``` 

4. Delete nginx1 pod and source-pvc
```shell
# kubectl delete pods nginx1
# kubectl delete pvc source-pvc
``` 

5. Create a pvc with source-pvc-snapshot， named snapshot-pvc
```shell
# cat snapshot-pvc.yml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-pvc
spec:
  storageClassName: hwameistor-storage-lvm-hdd
  dataSource:
    name: source-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
``` 

6. Create a pod use snapshot-pvc，named nginx2
```shell
# cat nginx-clone.yml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: default
spec:
  containers:
  - name: nginx
    image: ecr-sh.yun.qianxin-inc.cn/alkaid/nginx:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: data
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: snapshot-pvc
``` 

**Pod Info**
```shell
# kubectl describe pods nginx2 
...
...
Events:
  Type     Reason            Age                  From                  Message
  ----     ------            ----                 ----                  -------
  Warning  FailedScheduling  24m                  hwameistor-scheduler  0/1 nodes are available: 1 PersistentVolumeClaim "source-pvc" not found. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
  Warning  FailedScheduling  3m59s (x3 over 18m)  hwameistor-scheduler  0/1 nodes are available: 1 PersistentVolumeClaim "source-pvc" not found. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
``` 

**What you expected to happen**
After pvc create volumesnapshot， beforce create pvc with volumesnapshot，source pvc could delete and do not affect createion of pod

**Comment by SSmallMonster** [comment]
>4. Delete nginx1 pod and source-pvc
> \# kubectl delete pods nginx1
> \# kubectl delete pvc source-pvc

For now, we don't support snapshot restore after source volume was deleted. So, a scheduling error will occur when use snapshot like this.

But we have already planned to support this situation with some 'delay deletion' policy. This makes sense for scenarios such as Kubevirt's snapshot restore.

**Comment by liyang516** [comment]
> > 4. Delete nginx1 pod and source-pvc
> >    # kubectl delete pods nginx1
> >    # kubectl delete pvc source-pvc
> 
> For now, we don't support snapshot restore after source volume was deleted. So, a scheduling error will occur when use snapshot like this.
> 
> But we have already planned to support this situation with some 'delay deletion' policy. This makes sense for scenarios such as Kubevirt's snapshot restore.

tks
