### ISSUE TITLE
use SourceVolume allocated capacity as size_bytes

### ISSUE THREAD

**Issue by SSmallMonster** [hwameistor/hwameistor#1243]
`size_bytes` returned by CSI CreateSnapshot/ListSnapshot will be used for limiting the minimum size of volume required to create a volume from this snapshot. 

> https://github.com/hwameistor/hwameistor/blob/c0e1d64a7e9e6f53357edcf75bd8da0ed5b9da2c/pkg/local-storage/member/csi/controller.go#L1059C24-L1059C24

Thus, this size should be the capacity of source volume allocated capacity.

**NOTES:** this capacity check has implemented at 

> https://github.com/hwameistor/hwameistor/blob/c0e1d64a7e9e6f53357edcf75bd8da0ed5b9da2c/pkg/local-storage/member/csi/controller.go#L556C5-L556C26

Thus, this won't cause any error but should be improved.

**Comment by hikariwo** [comment]
Does it mean skip the request specified `snapsize` but using the source volume allocated capacity instead?
