### ISSUE TITLE
画眉在一开始安装时没有开启高可用，后续还能开启高可用嘛

### ISSUE THREAD

**Issue by lpl-oos** [hwameistor/hwameistor#1252]
Output of `lsblk`:
```
# paste output here
```

Output of `blkid`:
```
# paste output here
```

Output of `kubectl version`:
```
# paste output here
```

Output of `kubectl get lsn -o yaml`:
```
# paste output here
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```
![c2c5aa780a6b4f99bbd8af79eec020c](https://github.com/hwameistor/hwameistor/assets/59161158/aff5f56e-306c-46fe-8f19-88b014bf94a0)

**Comment by SSmallMonster** [comment]
Yes, the HA module should be actived after installation. Is there any problem have you meeted?
