### ISSUE TITLE
local-disk-manager: protential wrong devlink may be found when LocalDiskVolume create link to pool disk

### ISSUE THREAD

**Issue by hikariwo** [hwameistor/hwameistor#1254]
Protential wrong devlink may be found when LocalDiskVolume create link to pool disk. When the LocalDiskVolume is in a state of creating, Its field `.Status.DevLinks` carries the devlinks and the devType that are owned by LocalDisk. And a final path cut will be created as a soft link by LocalDiskClaim.  Considering a scenario,`/etc/hwameistor/LocalDisk_PoolHDD/disk/devlink1` and `/etc/hwameistor/LocalDisk_PoolSSD/disk/devlink2` both exist in system. The LocalDiskVolume field Status.DevLinks are `by-id/abc/devlink1` and `by-id/def/devlink2` and `devType` is `HDD`.In current situation,it will consider the `selectedDisk` as `devlink2` and create a soft link to `../disk/devlink2` from `/etc/hwameistor/LocalDisk_PoolHDD/volume/{ldvName}`.However,`/etc/hwameistor/LocalDisk_PoolHDD/devlink2` is not an existed path. so the `devType` must be taken into consideration when find a specified pool disk.

**Comment by SSmallMonster** [comment]
@hikariwo What's the steps that we can reproduce this problem?

**Comment by hikariwo** [comment]
In this sample,it comes from a rare situation that the `SSD` disk having one devlink have a same suffix with another `HDD` disk devlink. Such as `HDD` having the devlink likes `by-id/abc/devlink1`,`by-id/def/devlink2`, and the `SSD` having the devlink likes `by-id/hello/devlink2`,`by-id/world/devlink3`. The  LocalDiskVolume choose the `HDD` as the disk it links. The problem will occurs

> @hikariwo What's the steps that we can reproduce this problem?

**Comment by hikariwo** [comment]
> > In this sample,it comes from a rare situation that the `SSD` disk having one devlink have a same suffix with another `HDD` disk devlink. Such as `HDD` having the devlink likes `by-id/abc/devlink1`,`by-id/def/devlink2`, and the `SSD` having the devlink likes `by-id/hello/devlink2`,`by-id/world/devlink3`. The LocalDiskVolume choose the `HDD` as the disk that it links. The problem will occur
> > > @hikariwo What's the steps that we can reproduce this problem?
> 
> The only thing I can think of that could cause this problem is a duplicate serial number. However, in this case, we recommend that users ensure that the serial number is not duplicated when adding disks. In addition, the logic we add cannot achieve 100% security. Instead, it makes our logic very complex and difficult to maintain.

Actually, it's just a sample. The key point is that it may find another disk type pool when it was specified a disk type. It may cause a link wrong
