### ISSUE TITLE
Migrate HA volume error

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#126]
![图片](https://user-images.githubusercontent.com/76234281/183345460-638bd82d-1a40-4ba7-9fed-c55d122343b9.png)

![图片](https://user-images.githubusercontent.com/76234281/183345675-0c62c5a0-f9d5-449a-8869-94602cd46c46.png)
![图片](https://user-images.githubusercontent.com/76234281/183345694-93ebe8cd-2a5e-4b25-88e9-319fdd906cd9.png)

**Comment by angel0507** [comment]
we have fixed it at https://github.com/hwameistor/hwameistor/pull/157
