### ISSUE TITLE
the lvr and lvg data are inconsistent

### ISSUE THREAD

**Issue by wwwnay** [hwameistor/hwameistor#1276]
hwameistor version 
```
[root@controller-node-1 ~]# helm list -n hwameistor
NAME               	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION
hwameistor-operator	hwameistor	5       	2023-11-14 12:58:26.176442229 +0000 UTC	deployed	hwameistor-operator-v0.13.1	v0.13.1
```

the same pv `pvc-09df41ba-9079-48d4-bf4d-bc38a3407405` ,lvg shows node [controller-node-1,worker-node-2], lvr shows node  [controller-node-1,worker-node-1]
```
[root@controller-node-1 ~]# kubectl get lvg 2d9af1be-6b05-4d0f-af4e-ea44c42ead56 -o yaml
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeGroup
metadata:
  creationTimestamp: "2023-11-28T01:50:58Z"
  finalizers:
  - hwameistor.io/localvolumegroup-protection
  generation: 4
  name: 2d9af1be-6b05-4d0f-af4e-ea44c42ead56
  resourceVersion: "9880867"
  uid: eb929d90-3d3d-49f2-8490-305443c440c9
spec:
  accessibility:
    nodes:
    - controller-node-1
    - worker-node-2
    regions:
    - default
    zones:
    - default
  namespace: default
  volumes:
  - localvolume: pvc-09df41ba-9079-48d4-bf4d-bc38a3407405
    pvc: tk-c-tk-0
```

```
[root@controller-node-1 ~]# kubectl get lvr
NAME                                              CAPACITY      NODE                STATE         SYNCED   DEVICE                                                                  AGE
pvc-09df41ba-9079-48d4-bf4d-bc38a3407405-22kf6n   1073741824    worker-node-1       Ready         true     /dev/LocalStorage_PoolHDD/pvc-09df41ba-9079-48d4-bf4d-bc38a3407405      13m
pvc-09df41ba-9079-48d4-bf4d-bc38a3407405-xkmjqh   1073741824    controller-node-1   Ready         true     /dev/LocalStorage_PoolHDD/pvc-09df41ba-9079-48d4-bf4d-bc38a3407405      5m31s
```

**Comment by hikariwo** [comment]
I suggest adding a sync logic when the LocalVolume was updated. Maybe it is efficient to make the LocalVolumeGroup access node same as the LocalVolumeReplicas node

**Comment by SSmallMonster** [comment]
>adding a sync logic for LocalVolumeGroup when the LocalVolume was updated

this should be added already at: https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L93-L97

this makes accessability in volumegroup keep same with associated volume.

**Comment by SSmallMonster** [comment]
> > > adding a sync logic for LocalVolumeGroup when the LocalVolume was updated
> > 
> > 
> > this should be added already at:
> > https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L93-L97
> > 
> > this makes accessability in volumegroup keep same with associated volume.
> 
> But if the LocalVolume access node is updated when len(lvg.Spec.Accessibility.Nodes) > 0, the sync will be broken.

why say so, in my opinion, this is the common case when ha-volume is created. 

can you paste the source to explain this?

**Comment by hikariwo** [comment]
https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L576-L581

> > > > adding a sync logic for LocalVolumeGroup when the LocalVolume was updated
> > > 
> > > 
> > > this should be added already at:
> > > https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L93-L97
> > > 
> > > this makes accessability in volumegroup keep same with associated volume.
> > 
> > 
> > But if the LocalVolume access node is updated when len(lvg.Spec.Accessibility.Nodes) > 0, the sync will be broken.
> 
> why say so, in my opinion, this is the common case when ha-volume is created.
> 
> can you paste the source to explain this?

It found a matched LocalVolumeName in lvg,but if len(lvg.Spec.Accessibility.Nodes) > 0,the lvg access node will not be updated

**Comment by hikariwo** [comment]
> > > > adding a sync logic for LocalVolumeGroup when the LocalVolume was updated
> > > 
> > > 
> > > this should be added already at:
> > > https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L93-L97
> > > 
> > > this makes accessability in volumegroup keep same with associated volume.
> > 
> > 
> > But if the LocalVolume access node is updated when len(lvg.Spec.Accessibility.Nodes) > 0, the sync will be broken.
> 
> why say so, in my opinion, this is the common case when ha-volume is created.
> 
> can you paste the source to explain this?

https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L576-L581
It found a matched LocalVolumeName in lvg,but if len(lvg.Spec.Accessibility.Nodes) > 0,the lvg access node will not be updated

**Comment by SSmallMonster** [comment]
> > > > > adding a sync logic for LocalVolumeGroup when the LocalVolume was updated
> > > > 
> > > > 
> > > > this should be added already at:
> > > > https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L93-L97
> > > > 
> > > > this makes accessability in volumegroup keep same with associated volume.
> > > 
> > > 
> > > But if the LocalVolume access node is updated when len(lvg.Spec.Accessibility.Nodes) > 0, the sync will be broken.
> > 
> > 
> > why say so, in my opinion, this is the common case when ha-volume is created.
> > can you paste the source to explain this?
> 
> https://github.com/hwameistor/hwameistor/blob/d2bc8904d7ce020571a470b38e9e7d24ce46b2fc/pkg/local-storage/member/controller/volumegroup/manager.go#L576-L581
> 
> 
> It found a matched LocalVolumeName in lvg,but if len(lvg.Spec.Accessibility.Nodes) > 0,the lvg access node will not be updated

yes, this may cause a problem when volume accessability updated after `convert`, `migrate` happens. 

@wwwnay is there any operations like `migrate` or `convert` ever happend to this volume?

**Comment by wwwnay** [comment]
I did not perform any migrate or convert operations; 
I just created an STS and stopped it after it was running successfully, intending to perform the migration operation ，then i find this issue
