### ISSUE TITLE
[docs] Does HwameiStor support OpenShift and Ranch

### ISSUE THREAD

**Issue by sun7927** [hwameistor/hwameistor#128]
Need to test and clarify if HwameiStor can work with OpenShift and Ranch besides the Kubernetes.

1. Need to test if HwameiStor can work with OpenShift and Rancher
2. Document should be updated with this information.

**Comment by alexzhc** [comment]
HwameiStor can work on Rancher right out of box, but needs a lot of extra work for OpenShift because it implements full k8s security features and also has its own security CRD `SCC`. HwameiStor's LDM and LS modules need very high privilege to work, therefore SCC must be carefully configured.

**Comment by alexzhc** [comment]
What dev will have to do
1. Setting up Openshift and Rancher test clusters
1. Test hwameistor on it
1. Adjust helm charts to adapt to "the extra requirements (if there are)" of Openshift and Rancher

Dev estimates that under the current schedule, it will take at least a month to complete it. 

Therefore, for now, it is probably only appropriate to state that "Openshfit and Rancher are not supported yet"

**Comment by alexzhc** [comment]
Another obstacle is that Openshift uses its own OS RHCOS (formerly CoreOS).
