### ISSUE TITLE
[Large scale test]Create 1000 applications and bind them to pvc, then delete the application and pvc, but the lv is not deleted automatically.

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1306]
Create 1000 applications and bind them to pvc, then delete the application and pvc, but the lv is not deleted automatically.

```
[root@k8s-master ~]# kubectl get lv |wc -l
313
[root@k8s-master ~]# kubectl get pvc
No resources found in default namespace.
[root@k8s-master ~]# kubectl get pv
No resources found
```
This situation will occur when deleting the pvc when the lv has been created but the corresponding pv has not been successfully created.

**Comment by SSmallMonster** [comment]
can you provide `csi-provisoner` container log and `member` container log of local-storage?
