### ISSUE TITLE
hwameistor0.10.8 删除 pcv  pv 和主机节点上LV后部分节点hwameistor 显示容量没回收

### ISSUE THREAD

**Issue by ihuibin** [hwameistor/hwameistor#1310]
<img width="1531" alt="image" src="https://github.com/hwameistor/hwameistor/assets/18320100/aaebbca7-ce17-47e5-b354-f942017aa650">

使用kubectl edit  lv   he kubectl edit  lvr   delete  标记为true 同样显示存储没回收，并且节点上的也已经lvremove

**Comment by SSmallMonster** [comment]
@ihuibin To reclaim storage capacity, there are serval points to focus on:

* make sure all volumes on the devices **ARE NEVER USED** later and cleand
* make sure pv has been already removed from vg LocalStorage_XXX
* make sure filesystem on the device has been wiped

after all these steps done, you can delete the coresponding LocalDisk object and restart the local-disk-managed pod located on the device attached node.
