### ISSUE TITLE
新部署的应用，既要创建一个卷（该卷小于剩余空间），又要复用已存在的一个卷（该卷大于剩余空间），会创建不成功。

### ISSUE THREAD

**Issue by XC-L** [hwameistor/hwameistor#1311]
hwameistor-operator-v0.13.1

步骤如下：
1. 通过yaml部署一个2048，请求一个150G的卷，存储配置如下
<img width="258" alt="image" src="https://github.com/hwameistor/hwameistor/assets/38427005/4ab42ab9-7bdd-49aa-84f1-e66bf5a9f371">

此时pvc、pod创建成功。

2. 此时vg还剩余19G空间（小于150G）
<img width="482" alt="image" src="https://github.com/hwameistor/hwameistor/assets/38427005/0868902d-e2e4-462d-b0fa-1120f6fef1c4">

3. 通过yaml部署再一个2049，请求一个1G的卷，以及复用之前的150G的卷，存储配置如下
<img width="281" alt="image" src="https://github.com/hwameistor/hwameistor/assets/38427005/a9a79e9c-50b1-442a-b4ca-bd783530e593">

此时，该2049的pod没创建出来，并导致1G的卷状态为Pending。

<img width="1161" alt="image" src="https://github.com/hwameistor/hwameistor/assets/38427005/696a4a65-2c47-4220-ad18-eaec31f87011">

hwameistor-scheduler的日志有个error，表示节点上总共200G，已经分了180多G，又请求了150G，没空间了
<img width="1438" alt="image" src="https://github.com/hwameistor/hwameistor/assets/38427005/252a4594-639e-4327-95e9-a296c66c9101">

4. 如果2048它请求的存储卷是1G，那再部署2049也是没问题的。如果2049仅仅复用2048的存储卷，没有新请求存储卷的话，部署也是没问题的。

**Comment by peng9808** [comment]
@XC-L   I tried to reproduce this problem, but the above problem was not reported. Can you update to the latest version and try again?
