### ISSUE TITLE
[Doc] Enhance the document's structure 

### ISSUE THREAD

**Issue by sun7927** [hwameistor/hwameistor#132]
Suggested the new structure of document as below:

1. What's the HwameiStor
2. Quick Start
    2.1 Installations
    2.2 Start a Stateful Application
           2.2.1 Basic Operations
           2.2.2 Advanced Operations
    2.3 Advanced Features
           2.3.1 Node Expansion
           2.3.2 Disk Expansion
           2.3.3 Upgrade
     2.4 Uninstall
3. Architecture of HwameiStor
    3.1 Overview
    3.2 Components
    3.3 Resources
    3.4 APIs
4. Development Designs (Optional)
5. Applications
    5.1 TiDB
    5.2 MinIO
    ...
6. Terminologies
7. Community
8. FAQs

**Comment by alexzhc** [comment]
working on a doc pr.
