### ISSUE TITLE
it has 11 nodes in my cluster, however there are only 9 record in storage nodes

### ISSUE THREAD

**Issue by liyuerich** [hwameistor/hwameistor#1329]
it has 11 nodes in my cluster, however there are only 9 record in storage nodes

1 node is disk pressure, 1 node is unknown. from my view, it should show all nodes status.

![image](https://github.com/hwameistor/hwameistor/assets/97269208/efb62e1b-8788-4e35-9cf4-e258edc6f098)

**Comment by SSmallMonster** [comment]
@liyuerich Thanks for your feedback. 
Can you check if the missing node has the label `lvm.hwameistor.io/enable=false` above it? If there is this label, the node will not be nano-piped as a storage node, unlike the k8s nodes.
