### ISSUE TITLE
Residual LocalVolume information causes an error

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#135]
time="2022-08-09T03:27:30Z" level=debug msg="Finished running command" func=RunCommand file="executor.go:92" args="[--mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net --uts=/proc/1/ns/uts -- lvcreate --size 1073741824B --stripes 1 LocalStorage_PoolHDD -n pvc-4deca8ca-0258-49a6-85b9-3efb5670f7f8 -y]" command=nsenter error="exit status 5" stderr="  Logical Volume \"pvc-4deca8ca-0258-49a6-85b9-3efb5670f7f8\" already exists in volume group \"LocalStorage_PoolHDD\"" stdout= timeout=30

**Comment by angel0507** [comment]
thanks for your issue , it has already fixed at https://github.com/hwameistor/hwameistor/pull/160
