### ISSUE TITLE
一个计算节点挂了，三个miniopod无法启动，导致 minio 不健康

### ISSUE THREAD

**Issue by ihuibin** [hwameistor/hwameistor#1359]
一个计算节点挂了，导致 minio 不健康，今天把节点拉起来后，其中一个minio，有个pod不正常，我们删除pvc后变成健康。还有个minio 有三个pod起不来，报错如下 0/10 nodes are available: 10 lvm is being migrated, 3 node(s) had untolerated taint {node-role.kubernetes.io: master}. preemption: 0/10 nodes are available: 3 Preemption is not helpful for scheduling, 7 No preemption victims found for incoming pod.

<img width="966" alt="企业微信截图_17055525285534" src="https://github.com/hwameistor/hwameistor/assets/18320100/c2dc4baa-1e04-443c-9c70-20918ec545f6">
<img width="966" alt="企业微信截图_17055529199242" src="https://github.com/hwameistor/hwameistor/assets/18320100/5448be1f-7d54-4cd6-990f-31a3ed48b8e6">

**Comment by SSmallMonster** [comment]
fixed.
