### ISSUE TITLE
支持 Physical Volume (PV) 自动故障隔离

### ISSUE THREAD

**Issue by nashtsai** [hwameistor/hwameistor#1366]
是否可以扩展 Physical Volume (PV) 自动故障隔离？(扫描了代码 没有调用 `pvmove` `vgreduce`)

**Comment by SSmallMonster** [comment]
@nashtsai Thanks for your feedback.

This is a very practical suggestion. In a production environment, failures are inevitable, and the disk, data volume, and nodes may all be potential points of failure. We have already made some attempts for these scenarios, including isolation and recovery at the data volume level. These features(we call ai-ops including fault-management, fault-detect...) are not fully ready yet, but if you have any specific requirements, feel free to describe them.
