### ISSUE TITLE
在部署0.7、0.8版本的时候，Hwamei还不能选择高可用的PVC，到后期版本后，Hwamei可以创建高可用了，在PV有数据的情况下，怎么升级Hwamei实现高可用并且不影响原有数据

### ISSUE THREAD

**Issue by jzhupup** [hwameistor/hwameistor#1377]
是否可以提供一些相关思路步骤，来进行操作

**Comment by dchjingyue** [comment]
这个需求的背景当初是镜像仓库底层采用的画眉创建的lv存放数据，最初想法是把harbor的数据存储pv转换成高可用pv，但是经过多方对比发现harbor镜像仓库高可用可以采用minio来替代画眉高可用pv，故这里的需求不是那么急迫。
