### ISSUE TITLE
【hwameistor】After the hwameister scheduler and admission controller nodes are down, pod startup cannot find the local volume

### ISSUE THREAD

**Issue by fangbin9527** [hwameistor/hwameistor#1384]
Description:  
After the hwameister scheduler and admission controller nodes are down, pod startup cannot find the local volume  

    
    
log information：
1、hwameistor 
![企业微信截图_17062496075553](https://github.com/hwameistor/hwameistor/assets/71134088/d26d809d-5b83-4123-bd12-c7c7500d41e9)  
2、The corresponding pod is consistent during initialization
![企业微信截图_1706249445597](https://github.com/hwameistor/hwameistor/assets/71134088/b5c52e76-9203-4707-9939-d86fe2fff5be)
3、events
![企业微信截图_17062494532581](https://github.com/hwameistor/hwameistor/assets/71134088/05581a6b-608b-435b-be2a-bd98c0d4a206)

notes：
Restore normal operation after restarting minio-pod

**Comment by SSmallMonster** [comment]
@fangbin-Li 

This seems like a scheduler fault. 

Based on the information you provided, after the admission POD goes down, the Minio POD probably used the default scheduler for scheduling, which resulted in it being scheduled to the wrong node. To avoid this problem, you can change the Admission's policy from `Ignore` to `Failure`, so that the Minio POD will keep waiting until the hwameistor system is fully operational before it is scheduled.

**Comment by sundegan** [comment]
Hi @SSmallMonster,

I'm very interested in contributing to this issue as it aligns with my current learning objectives and my passion for cloud-native technologies.   I have a solid background in Go language development and I am actively seeking to deepen my understanding and experience with Kubernetes and other cloud-native projects.

I am relatively new to this specific project, but I am very eager to learn and contribute in any way that I can.   Could you please provide some guidance or point me towards the relevant documentation or parts of the codebase that would help me understand the issue better?

While I am new, I am very motivated and willing to invest the necessary time to become an effective contributor to this project.   I appreciate any guidance or advice you can provide to help me get started.

Thank you for your time and for maintaining such a valuable project.   I look forward to your reply and hope to contribute to the community soon.

Best regards,
sundegan

**Comment by SSmallMonster** [comment]
> Hi @SSmallMonster,
> 
> I'm very interested in contributing to this issue as it aligns with my current learning objectives and my passion for cloud-native technologies. I have a solid background in Go language development and I am actively seeking to deepen my understanding and experience with Kubernetes and other cloud-native projects.
> 
> I am relatively new to this specific project, but I am very eager to learn and contribute in any way that I can. Could you please provide some guidance or point me towards the relevant documentation or parts of the codebase that would help me understand the issue better?
> 
> While I am new, I am very motivated and willing to invest the necessary time to become an effective contributor to this project. I appreciate any guidance or advice you can provide to help me get started.
> 
> Thank you for your time and for maintaining such a valuable project. I look forward to your reply and hope to contribute to the community soon.
> 
> Best regards, sundegan
@sundegan Cool, it's open community, feel free to participate.

You can start by simply installing and using Hwameistor to familiar with the system components and how it works.

Once you're very familiar with how to use it, I'm sure you'll find some issues along the way, whether it's with the code or the documentation or whatever, and you can participate by submitting a PR.
It is recommended to start with some simple questions and slowly get deeply involved.

If you have any questions, we can communicate with you in PR or Issue.

**Comment by sundegan** [comment]
@SSmallMonster 

Thank you for your encouragement and guidance.  I've successfully completed the installation and deployment of the project, and have also gone through a preliminary study of Kubernetes to better understand the context and background.

I have started to explore the source code to get a better feel for the project structure and coding practices.  I agree with your recommendation about starting with simple issues to get more deeply involved.  To this end, I've been considering tackling a straightforward issue to further my understanding and contribute effectively.

I would like to ask for your advice on reading the source code.  Are there any specific parts of the project or modules that you recommend I start with?  Also, do you have any suggestions on the order of reading or key areas I should focus on to better understand the overall architecture and most critical paths of the code?

I'm eager to make a meaningful contribution and continue learning about the project and cloud-native technologies.  I appreciate your support and look forward to your advice.
