### ISSUE TITLE
画眉UI中，扩容等操作在详情页面无可操作项

### ISSUE THREAD

**Issue by Rei1010** [hwameistor/hwameistor#1386]
Output of `lsblk`:
```
# paste output here
```

Output of `blkid`:
```
# paste output here
```

Output of `kubectl version`:
```
# paste output here
```

Output of `kubectl get lsn -o yaml`:
```
# paste output here
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```

**Comment by peng9808** [comment]
@Rei1010 The latest version already supports

**Comment by peng9808** [comment]
@Rei1010 The latest version already supports![企业微信截图_58664886-02d8-49a9-bfed-9371d72b58d7](https://github.com/hwameistor/hwameistor/assets/144866407/8a754c9c-9558-43dd-8f54-0b47de52dd4d)
