### ISSUE TITLE
Partitions should be supported

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#1387]
At present, hwameistor is disk-oriented, but in some cases, this does not apply.  

For example: I got a k8s cluster running on a laptop, while the laptops usually own only one disk. And I can't use disk partitions, even though partitions have a lot of capacity.

Maybe we should come up with a solution for covering this case.

**Comment by SSmallMonster** [comment]
work-around docs: https://hwameistor.io/docs/faqs#q6-how-to-expand-the-storage-pool-manually
