### ISSUE TITLE
timeplus部署原使用local sc，改进使用画眉做存储支撑

### ISSUE THREAD

**Issue by xiaoshiliuxx** [hwameistor/hwameistor#1388]
标准版部署的sc和pv需要手动创建，如下
![1](https://github.com/hwameistor/hwameistor/assets/78410212/79ab0866-f1ec-4939-ba91-d9e5b535cad2)
![2](https://github.com/hwameistor/hwameistor/assets/78410212/e94bbad7-2643-4a56-a65a-fe7d169ed9ad)
如果直接画眉会造成报错

**Comment by xiaoshiliuxx** [comment]
![微信图片_20240202084309](https://github.com/hwameistor/hwameistor/assets/78410212/ca47d60b-8fce-4f99-8a62-9d6200a297da)

**Comment by peng9808** [comment]
In Kubernetes, persistent volume claims (PVCs) do not directly support selectors. PVCs bind PVs based on access mode, storage capacity, and storage class, but direct PVC selectors are not part of the Kubernetes PVC specification.
