### ISSUE TITLE
hwameistor-apiserver error " write :broken pipe "

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1418]
```
ab -c 100 -n 10000 http://10.6.113.39:32722/apis/hwameistor.io/v1alpha1/cluster/nodes?page=1&pageSize=1
```
![企业微信截图_17103812901429](https://github.com/hwameistor/hwameistor/assets/76234281/378c89b0-2fbb-4215-9e8a-e6c9f4a5f059)

**Comment by sundegan** [comment]
I would like to try to solve this problem, which seems to be caused by the server taking too long to process, causing the client to shut down in a timeout?
