### ISSUE TITLE
【ui】With Hwameistor, you can migrate without selecting a source node first, just click to start

### ISSUE THREAD

**Issue by yt-huang** [hwameistor/hwameistor#1428]
version：hwameistor-operator:v0.14.4

<img width="867" alt="image" src="https://github.com/hwameistor/hwameistor/assets/33514158/ae786b14-9e0e-44aa-95e3-8539970d0216">

<img width="808" alt="image" src="https://github.com/hwameistor/hwameistor/assets/33514158/bfbd6cdf-dc8d-44c1-9fd2-23b518d5e75d">

**Comment by SSmallMonster** [comment]
Yes, error should be catched and showen to user when source node has't specified.

```shell
{"errcode":203,"description":"SrcNode cannot be empty or cannot be string"}
```
