### ISSUE TITLE
After the disk is bound, there is no capacity in the lsn

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1449]
![1af054e9-a9b0-4cb3-97c8-3dd49dcc3239](https://github.com/hwameistor/hwameistor/assets/76234281/0e266bd0-7b8f-4a08-98c4-aafe090d3a23)
![734c4dfe-ad47-4206-8966-063f18139195](https://github.com/hwameistor/hwameistor/assets/76234281/9060d3ec-2614-402b-833f-5f004cf0527f)

[hwameistor-local-disk-manager-2b5pp.log](https://github.com/hwameistor/hwameistor/files/15104977/hwameistor-local-disk-manager-2b5pp.log)
[hwameistor-local-storage-bvcr2-member.log](https://github.com/hwameistor/hwameistor/files/15104978/hwameistor-local-storage-bvcr2-member.log)

**Comment by FloatXD** [comment]
Caused by the same disk serial numbers on different nodes

**Comment by SSmallMonster** [comment]
work-around docs: https://hwameistor.io/docs/faqs#q6-how-to-expand-the-storage-pool-manually
