### ISSUE TITLE
[docs] Added a glossary list to keep consistency

### ISSUE THREAD

**Issue by windsonsea** [hwameistor/hwameistor#145]
Much inconsistency is found in docs. It's time to add a glossary list, so everyone can follow the glossary and reduce confusion. Starting from four modules of HwameiStor:

- local-disk-manager
- local-storage
- scheduler
- admission-controller
- HwameiStor

Hope we add more day by day.

**Comment by sun7927** [comment]
Great! Can you help to check the documents and correct the inconsistent?

**Comment by sun7927** [comment]
Please add a section of glossary in the documents.
