### ISSUE TITLE
If the disk serial numbers of different nodes are the same, hwameistor cannot manage the disk normally.

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1450]
![7d9d42cb-98b0-46a3-a15b-f054a517f328](https://github.com/hwameistor/hwameistor/assets/76234281/7cd8117b-464e-4b80-92d7-d5784773673a)

If the disk serial numbers of different nodes are the same, hwameistor cannot manage the disk normally.ld will be overwritten. Is there any detailed solution?

**Comment by FloatXD** [comment]
This situation will occur if the disk serial numbers of different nodes are the same.

**Comment by SSmallMonster** [comment]
work-around docs: https://hwameistor.io/docs/faqs#q6-how-to-expand-the-storage-pool-manually
