### ISSUE TITLE
Failed to expand storage capacity, err: exit status 5

### ISSUE THREAD

**Issue by Catherine-monk** [hwameistor/hwameistor#1453]
Output of `lsblk`:
<img width="597" alt="image" src="https://github.com/hwameistor/hwameistor/assets/59492260/868c3f8c-fd6f-4f3f-9acc-545a583c1030">
# paste output here

Output of `blkid`:
<img width="792" alt="image" src="https://github.com/hwameistor/hwameistor/assets/59492260/9c0cd5e6-ebde-40db-8126-6f57026fe6be">
# paste output here
```



Output of `kubectl version`:
<img width="781" alt="image" src="https://github.com/hwameistor/hwameistor/assets/59492260/813e33bb-97eb-4d40-8d3a-a8c053128e42">
# paste output here



Output of `kubectl get lsn -o yaml`:
<img width="648" alt="image" src="https://github.com/hwameistor/hwameistor/assets/59492260/470ab4a7-a62d-4bb9-9d26-f19cc2424d82">
# paste output here



Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```

**Comment by SSmallMonster** [comment]
@Catherine-monk Thanks for your feedback.

Can you paste the origin error message? I'm not sure which component the error message come from(local-storage, local-disk-manager)...

**Comment by Catherine-monk** [comment]
After deleting the corresponding ld, and then restarting the local-disk-manager pod, the error was resolved.
The issue cannot be reproduced at the moment.
