### ISSUE TITLE
[docs] Added a style guide

### ISSUE THREAD

**Issue by windsonsea** [hwameistor/hwameistor#146]
HwameiStor documentation has three different topics currently. It is recommended to provide a simple style guide if more than 20 topics in a docsite.

- Concept
- Task (steps)
- Reference

References:
- [Kubernetes Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/)
- [Simple English Writing Style Guide](https://dwiki.daocloud.io/display/~haifeng.yao/General+Writing+Guidelines)

**Comment by windsonsea** [comment]
# Images

It is welcomed if you can draw some diagrams about architecture, modules, principle, features desc, etc. 

However, some images are not suggested, or even to avoid. For example, in a long blog, when you run a simple command and the system outputs something on your screen. In this case, it's better to directly copy/paste your on-screen text rather than a screenshot.

![image](https://user-images.githubusercontent.com/79828097/183791370-aff44bfb-2533-41b6-8d2c-de9b4b1aa655.png)

As shown above, it's difficult to control the resolution and pixels of an image to adapt to different hardware and cloud environment, and not easy to reproduce your dev, test, use environment. Few people may follow your screenshot to type the command letter by letter again because the user cannot copy!

**Comment by windsonsea** [comment]
## Tasks

A task refers to the topics that can tell your how to follow steps and get a result.

![image](https://user-images.githubusercontent.com/79828097/183793317-cdb2b90b-c7e1-4b77-ada2-3efa28b28615.png)

**Comment by windsonsea** [comment]
## Reference
A reference page may list many commands, flags, options, APIs, and more. When a user doesn't remember something, he/she will come to search for.

![image](https://user-images.githubusercontent.com/79828097/183793672-5f960317-1382-4534-a083-41f13d80dae1.png)

**Comment by windsonsea** [comment]
## Concepts

A concept describes what, when, why, where, and more. It will be a good topic of concept if you can add sufficient diagrams,  examples, and reference links.

![image](https://user-images.githubusercontent.com/79828097/183797002-78161e4c-1f62-4ed7-9e4d-1989f83ad1ee.png)

**Comment by windsonsea** [comment]
## Test report

A test report shall provide what is bad, not good, or weakness in addition to everything good. Sometimes, complaints are more useful than curry favor. We are technical-related!

Your sincerity can tell readers that you are striving to do something. If everything is always good enough, and no response and growth, the community is close to dead in practice.

**Comment by windsonsea** [comment]
## What is a solution?

A solution refers to combine different features into a package to deal with a scenario, and try to make a trouble easy.

In a solution, you should provide clear procedures, required features and components, and relevant resources. A solution has the feature of reproduction if you encounter the similar situation later.

**Comment by sun7927** [comment]
Can we add an auto-checker for the style of the document?

I strongly suggest to draft a wiki page for this style guide instead. I don't think "issue" is the good place to have it.

**Comment by windsonsea** [comment]
We can refer to [DaoCloud Style Guide of Writing](https://github.com/DaoCloud/DaoCloud-docs/blob/main/style.md). It is hosted on GitHub now.
