### ISSUE TITLE
If lvconvert is not successful, the replicas of lv should be 1

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1473]
As long as lvconvert is applied, the number of replicas will be 2, which is misleading.
```
[root@k8s-master ~]# kubectl get lv
NAME                                       POOL                   REPLICAS   CAPACITY     USED       STATE      PUBLISHED   AGE
pvc-4d9d6ae2-b909-42b8-b1de-4b986c204137   LocalStorage_PoolHDD   2          1073741824   33787904   Creating   k8s-node1   2m52s
```

**Comment by SSmallMonster** [comment]
when `LocalVolumeConvert` applied,  the volume replica in spec will be converted to 2 and staus will be changed to `Creating`. 

I think this is ok, can you describe why you this is misleading?

**Comment by peng9808** [comment]
I think so，this is ok
