### ISSUE TITLE
Affinity scheduling needs to be added to the documentation

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1477]
Affinity scheduling needs to be added to the documentation

**Comment by peng9808** [comment]
![f6a52763-e67a-4fee-9090-4292ea75eaec](https://github.com/user-attachments/assets/118bfc79-8157-4936-8081-79a7a4199991)
![731da100-7b12-4270-9d18-691fca7ced70](https://github.com/user-attachments/assets/5bdeaae1-e68f-4135-aff9-d87ecd0ea25b)
https://hwameistor.io/cn/docs/apps/ha
