### ISSUE TITLE
安装dce商业版失败，mcamel-common-es报错volume“ rpc error: code = Unknown desc = mount failed: exit status 32”

### ISSUE THREAD

**Issue by Catherine-monk** [hwameistor/hwameistor#1527]
报错：
![img_v3_02cm_18c89f59-dad1-4173-a45b-734e77acdfag](https://github.com/hwameistor/hwameistor/assets/59492260/86dbc680-bb99-4423-9006-31fc05c4b05d)

Output of `lsblk`:

<img width="1438" alt="image" src="https://github.com/hwameistor/hwameistor/assets/59492260/06a744c6-e52c-425f-8fd7-e450ecf46257">

**Comment by FloatXD** [comment]
Deleting pvc and pod can solve the problem
