### ISSUE TITLE
Failed to create PVC from snapshot

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1532]
![img_v3_02cr_3f7c8e88-c92f-4f16-b776-902bf497085g](https://github.com/user-attachments/assets/f93e9649-305a-4c83-a2ee-635d35260ac2)

**Comment by FloatXD** [comment]
```
error getting handle for DataSource Type VolumeSnapshot by Name test001: requested volume size 107374183 is less than the size 113246208 for the source snapshot test001
```
Increasing the capacity of PVC can solve the problem

**Comment by yt-huang** [comment]
When the stored size is 1 Gi, the restoration can be successful.

![image](https://github.com/user-attachments/assets/949e98de-079e-405d-95fc-2e4b256b6ecb)

![image](https://github.com/user-attachments/assets/b3cd9839-5980-4eef-ac72-de5e07091cbd)
