### ISSUE TITLE
dragonfly install failed 

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1533]
https://hwameistor.io/cn/docs/volumes/cache#%E5%AE%89%E8%A3%85-dragonfly
Install according to the documentation
![图片](https://github.com/user-attachments/assets/df4bb821-9862-45f4-94a1-c40262a22744)

**Comment by peng9808** [comment]
There is a conflict between the host's dfget and the socket generated inside the container. You need to wait until all pods run successfully before installing dfget on the host and restarting the pod.

**Comment by peng9808** [comment]
I will update the document as soon as possible
