### ISSUE TITLE
“hwameistor-scheduler” Not scheduled to the specified node

### ISSUE THREAD

**Issue by fangbin9527** [hwameistor/hwameistor#1534]
1.Node anti affinity yaml：  
![img_v3_02cu_dec52add-7702-4abc-95e8-5746cc5b81dg](https://github.com/user-attachments/assets/27f5341b-bd2b-4c07-93fa-7a6ceff58a22)  
2Scheduled to “controller-node”, expected not to be scheduled to “controller-node”  
![img_v3_02cu_d641e6e4-98b5-4070-9f66-064996c8efcg](https://github.com/user-attachments/assets/d3b63b9e-1aad-4c19-be53-980af340172c)  

3.hwameistor-scheduler logs
![image](https://github.com/user-attachments/assets/b830c0f7-923b-4a34-b63e-0bf36d9a36f9)  

4.hwameistor version  
ghcr.m.daocloud.io/hwameistor/scheduler:v0.14.5

**Comment by peng9808** [comment]
Due to the inability to reproduce the issue, it is inconvenient to investigate

**Comment by SSmallMonster** [comment]
please upgrade hwameistor version to v0.14.6 and re-test
