### ISSUE TITLE
[docs] Prerequisites is too simple

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#155]
The Prerequisites  is too simple.

![image](https://user-images.githubusercontent.com/1469319/184052016-f8281a2c-142a-4649-8316-c4f5dbf772cf.png)

Should we make it more detail? 
Like recommend Disk Size and OS for DRBD, I think it's very important information.

**Comment by alexzhc** [comment]
got it, will add more information

**Comment by alexzhc** [comment]
PR #162 has added more details for prerequisites.
