### ISSUE TITLE
Use rocky8 instead of centos7 to build the image, xfs has compatibility errors

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1553]
Compatibility issues related to xfs v4 and v5. The v5 file system (rocky) is not supported on v4 systems (centos 7, 8). may need to add some parameters.

**Comment by peng9808** [comment]
Maybe we can use the advantages of privileged containers to hand over the file system formatting and mounting to the host. Or recompile a rocky image with a lower version of the file system @SSmallMonster @FloatXD
