### ISSUE TITLE
intall hwameistor failed, error is exit status 5","file":"local_disk_claim_task_worker.go:136"

### ISSUE THREAD

**Issue by silence-0928** [hwameistor/hwameistor#1557]
Output of `lsblk`:

# paste output here
<img width="642" alt="image" src="https://github.com/user-attachments/assets/83df720b-2e30-4c8a-af3c-fa236856669f">

Output of `blkid`:

# paste output here
<img width="720" alt="image" src="https://github.com/user-attachments/assets/8a3e37de-050b-4059-b8bd-64eae244b932">

Output of `kubectl version`:

# paste output here
<img width="468" alt="image" src="https://github.com/user-attachments/assets/a187cf85-9eb7-47e0-83ed-abb625ff1ed6">

The error :
# paste output here
<img width="724" alt="image" src="https://github.com/user-attachments/assets/d0dbf891-daac-425c-8048-ccb8b3d1763d">

kubectl get ld
# paste output here
<img width="724" alt="image" src="https://github.com/user-attachments/assets/7130434b-e1a7-4f97-bd02-0cb7a38ecbac">

**Comment by SSmallMonster** [comment]
This issue has been fixed in https://github.com/hwameistor/hwameistor/pull/1524 and already involved in v0.14.6.

similar issue #1523
