### ISSUE TITLE
Mount volume failed after VM reboot (failed: Structure needs cleaning)

### ISSUE THREAD

**Issue by Rei1010** [hwameistor/hwameistor#1574]
![image](https://github.com/user-attachments/assets/f72ef58d-dd39-4fc5-a87a-a28d297d5b91)

**Comment by SSmallMonster** [comment]
Try to fix it by umount and mount volume again.

> [!WARNING]
Check if volume has umounted totally, in some case, pod has been deleted already but mount dir remained when using `--force` option.
