### ISSUE TITLE
文档描述错误 

### ISSUE THREAD

**Issue by hale177** [hwameistor/hwameistor#1578]
{ 数据卷/ 高可用卷 } 章节最下面， 本地卷创建节点的描述前后对应不上 ，应该都是：

**k8s-worker-1
k8s-worker-2**

![image](https://github.com/user-attachments/assets/fd77b776-d7fd-473a-b7bb-a000b16770f6)

**Comment by SSmallMonster** [comment]
resolved, thanks for your feedback. @hale177
