### ISSUE TITLE
HA volumes cannot be scheduled normally

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#168]
hwameistor-scheduler  0/4 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 3 no enough nodes.
![图片](https://user-images.githubusercontent.com/76234281/184101566-c4cbac3a-5ddb-4ce9-a799-bab509b26741.png)
apiVersion: hwameistor.io/v1alpha1
kind: LocalStorageNode
metadata:
  creationTimestamp: "2022-08-11T08:01:00Z"
  generation: 1
  name: k8s-node1
  resourceVersion: "4325660"
  uid: 2da10ee0-62ab-4d29-8ba6-54f921401fbe
spec:
  hostname: k8s-node1
  storageIP: 172.30.45.211
  topogoly:
    region: default
    zone: default
status:
  pools:
    LocalStorage_PoolHDD:
      class: HDD
      disks:
      - capacityBytes: 112738697216
        devPath: /dev/sdb
        state: Available
        type: HDD
      - capacityBytes: 21470642176
        devPath: /dev/sdc
        state: Available
        type: HDD
      freeCapacityBytes: 134209339392
      freeVolumeCount: 1000
      name: LocalStorage_PoolHDD
      totalCapacityBytes: 134209339392
      totalVolumeCount: 1000
      type: REGULAR
      usedCapacityBytes: 0
      usedVolumeCount: 0
      volumeCapacityBytesLimit: 134209339392
  state: Ready

apiVersion: hwameistor.io/v1alpha1
kind: LocalStorageNode
metadata:
  creationTimestamp: "2022-08-11T08:15:45Z"
  generation: 1
  name: k8s-node3
  resourceVersion: "4326897"
  uid: bd53ec10-fcd7-48af-a2ac-4a356ecc562f
spec:
  hostname: k8s-node3
  storageIP: 172.30.45.213
  topogoly:
    region: default
    zone: default
status:
  pools:
    LocalStorage_PoolHDD:
      class: HDD
      disks:
      - capacityBytes: 112738697216
        devPath: /dev/sdb
        state: Available
        type: HDD
      freeCapacityBytes: 112738697216
      freeVolumeCount: 1000
      name: LocalStorage_PoolHDD
      totalCapacityBytes: 112738697216
      totalVolumeCount: 1000
      type: REGULAR
      usedCapacityBytes: 0
      usedVolumeCount: 0
      volumeCapacityBytesLimit: 112738697216
  state: Ready

**Comment by SSmallMonster** [comment]
@FloatXD please use latest version to verify~
