### ISSUE TITLE
Convert the LVM volume first, and then migrate the volume will fail

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#188]
![图片](https://user-images.githubusercontent.com/76234281/184784780-929e6df9-b421-4f1e-8889-da52cbb6e61f.png)

![图片](https://user-images.githubusercontent.com/76234281/184784822-0d7cb78b-b088-4602-867f-baee470bf9a7.png)

**Comment by angel0507** [comment]
it looks like a bug ，we fixed it ,thanks your issue .

**Comment by sun7927** [comment]
Deadline: August

**Comment by angel0507** [comment]
Drbd state retain PauseSyncS, means the drbd synchronization dependency wait each other . So we donot advise convert maintainance and migrate maintainance running at the same time .
