### ISSUE TITLE
"ghcr.io/hwameistor/self-signed:v1" is not controlled by helm imageFlags

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#190]
Even when  `helm install` with below parameters:
```
--set k8sImageRegistry=$mylocalRegistry
--set hwameistorImageRegistry=$mylocalRegistry
```

the init container `"ghcr.io/hwameistor/self-signed:v1" ` still reach the internet of ghcr.io.

**Comment by panpan0000** [comment]
and its `imagePullPolicy: Always` makes no sense .

**Comment by SSmallMonster** [comment]
@panpan0000 Thanks for your feedback.
>Q1: the init container "ghcr.io/hwameistor/self-signed:v1" still reach the internet of ghcr.io.

You can use m.daocloud.io as your image repository, we have submitted a [PR](https://github.com/DaoCloud/public-image-mirror/pull/177) to synchronize the image

> and its imagePullPolicy: Always makes no sense .

We have update imagePullPolicy to `IfNotPresent` in https://github.com/hwameistor/hwameistor/pull/203
