### ISSUE TITLE
mutation webhook on the pod scheduling critical path

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#191]
when if the `hwameistor-admission-controller` breaks, the new pod will fail to be scheduled , the new running `rs` will complains:

```
Error creating: Internal error occurred: failed calling webhook "hwameistor.io.mutate-hook": 
failed to call webhook: Post "https://hwameistor-admission-controller.hwameistor.svc:443/mutate?timeout=10s":
 dial tcp 10.233.31.171:443: connect: connection refused
```

it's a bit dangerous.

**Comment by SSmallMonster** [comment]
@panpan0000 Thanks for your feedback.
The behavior when the callback fails can be configured as **Ignore**. This will user's request when `hwameistor-admission-controller` breaks.

Example:
```console
$ kubectl edit mutatingwebhookconfigurations hwameistor-admission-mutate

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
    name: hwameistor-admission-mutate
...
webhooks:
    failurePolicy: Ignore
    ....
```

**Comment by panpan0000** [comment]
what will happen if we `Ignore` this at the beginning? Will this config impact hwameiStore functionality ?

**Comment by SSmallMonster** [comment]
> what will happen if we `Ignore` this at the beginning? Will this config impact hwameiStore functionality ?

It will not affect the function of HwameiStor. The only impact is that the scheduler name when the application is created may not be modified, resulting in scheduling to nodes without storage capacity.
