### ISSUE TITLE
weird LDC concept which end-user should worry about

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#192]
currently, the quick start of hwameistor is awesome.
Applying a LDC for each one, then all free disk can be leveraged in k8s. great.
However, when my disk use up, I ** added new disk ** ( thanks to VMware , adding disk is easy) to VM.
But it requires another LDC to make those new disks can be recognized but k8s CSI.
although the naming of LDC (Local Disk Claim) means it's just like PVC, effect only once.
But forgetting the naming , just standing at the view point of end-user ,  the LDC seems more like internal concept , instead of concept which end-user should be worry about.

I've no suggestion , just a comment about this strange behavior  and concept design.

**Comment by SSmallMonster** [comment]
@panpan0000 Thanks for your suggestions.
The document is being improved, and it is expected that there will be a great improvement at the beginning of next month.

For the design of LDC, this is a good user feedback. We will reopen an issue to collect how to apply for disk and this resource positioning.
