### ISSUE TITLE
[Discussion] How to expand the storage capacity

### ISSUE THREAD

**Issue by SSmallMonster** [hwameistor/hwameistor#194]
# Purpose
How to trigger node storage capacity expansion？

Following points needing attention:
* Lightweight operation and maintenance
* Automation of expansion process
* Clear resource semantics

Relevant issue: https://github.com/hwameistor/hwameistor/issues/192

# What is the existing solution？
1. **Create a LocalDiskClaim** and specify the node and disk attribute
2. **Apply the LocalDiskClaim**

Example:
```shell
[root@demo-dev-master-01 ~]# cat << EOF | kubectl apply -f -
apiVersion: hwameistor.io/v1alpha1
kind: LocalDiskClaim
metadata:
    name: ldc-for-node1
spec:
  description:
    diskType: HDD
  nodeName: node1
EOF
```

## What's the problem?
1. The user needs to manually create a LocalDiskClaim.
2. For the user, he may have created a request to apply for the disk of the node, why do he need to request again?

**Comment by SSmallMonster** [comment]
Please leave your opinion on how to expand the capacity :-)

**Comment by panpan0000** [comment]
link with https://github.com/hwameistor/hwameistor/issues/192

**Comment by sun7927** [comment]
Expanding a node' storage capacity is one of actions for operating a Hwameistor system. It's one of solution to have another CRD like LocalStorageNodeExpand (LSNE) for node capacity expansion, and it will trigger the system to reconcile the LDC by searching for the new disk and add it into the node storage pool. When the operation completes, the CR(LSNE) will be deleted.

**Comment by sun7927** [comment]
Another solution is to add a new field (e.g. expansion: true/false) in the LDC for disk expansion. LS should monitor LDC for the field of expansion, and start to process it when the field is set to true.

**Comment by SSmallMonster** [comment]
> Another solution is to add a new field (e.g. expansion: true/false) in the LDC for disk expansion. LS should monitor LDC for the field of expansion, and start to process it when the field is set to true.

I think this scheme is good, but we will face a problem, that is, **if we apply multiple LDCs for one node, it will be confusing to process each LocalDiskClaim** at this time.
