### ISSUE TITLE
[minor] unnecessary steps during uninstall

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#199]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/14049268/184864660-899d8bbb-41ac-4595-84c1-cf77b9b67a3b.png">

it seems `helm uninstall` already clean up those 2 steps.

**Comment by alexzhc** [comment]
It is currently so for the purpose of clarification. There should eventually be a script for safe uninstallation.
