### ISSUE TITLE
[helm] very slow "helm install hwameistor/hwameistor" using online method

### ISSUE THREAD

**Issue by alexzhc** [hwameistor/hwameistor#201]
Using online method to do `helm install hwameistor/hwameistor` may take over 10 minutes (if ever successful) especially in China, because the chart URL `http://hwameistor.io/helm-charts` is hosted on github page. We need to offer alternative hosting for it or add acceleration to it. 

Suggest adding `http://helm.hwameistor.io` for alternative hosting.

**Comment by SSmallMonster** [comment]
Solutions:

1. helm repo add system https://release.daocloud.io/chartrepo/system
2. helm install hwameistor -n hwameistor system/hwameistor
