### ISSUE TITLE
Error creating: internal error occurred

### ISSUE THREAD

**Issue by xulongju** [hwameistor/hwameistor#222]
hello：
Upgrade from 0.3.4 to 0.3.5-rc. 0, and the error is as follows:
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/20881910/186141950-2585d7e2-b2c9-4400-a73b-4b2b3501a32a.png">

please help，thanks

**Comment by SSmallMonster** [comment]
Please check whether the namespace `hwameistor` has a label of **name: hwameistor**. If it does not exist, please add it manually.

Subsequently, we will check whether the necessary tags exist during startup.

**Comment by SSmallMonster** [comment]
fixed in https://github.com/hwameistor/hwameistor/pull/224
