### ISSUE TITLE
Upgrade hwameistor from 0.3.4 to 0.3.5-rc.0，no enough nodes

### ISSUE THREAD

**Issue by xulongju** [hwameistor/hwameistor#223]
hello，
Upgrade hwameistor from 0.3.4 to 0.3.5-rc.0，pvc not released
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/20881910/186327007-30b45f34-7bf7-4aab-9a53-0df2b8f5778a.png">

**Comment by SSmallMonster** [comment]
@xulongju Thanks for your feedback.
I think this is caused by a previously unused data volume leak. You can release the capacity manually
```shell
$ kubectl edit lv xxx 
spec:
    ...
   delete: true
   ...
```

**Comment by xulongju** [comment]
it.s ok,thanks
