### ISSUE TITLE
node label: master renamed to control-plane

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#230]
The label-selectors in yaml for hwameiStor  may involve something like 
```
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
``
but the new node  label becomes `      node-role.kubernetes.io/control-plane: ""`

my k8s is 1.24.4

I believe there's some solution from community .

**Comment by yankay** [comment]
master role [has been deprecated](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes):

Introduce a new label "node-role.kubernetes.io/control-plane" that will be applied in parallel to "node-role.kubernetes.io/master" until the removal of the "node-role.kubernetes.io/master" label.

**Comment by sun7927** [comment]
Deadline: Sept
