### ISSUE TITLE
The storage capacity of the scheduler does not include the allocated data volume capacity during initialization

### ISSUE THREAD

**Issue by SSmallMonster** [hwameistor/hwameistor#235]
![image](https://user-images.githubusercontent.com/22465917/186608455-16bdf583-60c5-4bf1-8cfe-028881ec8a85.png)

**Comment by sun7927** [comment]
test against the latest version.

**Comment by sun7927** [comment]
Deadline: August

**Comment by SSmallMonster** [comment]
The reason that the available capacity in the initialization phase is not correct is that the **LSN has not released the deleted LV volume**.

Therefore, we should check the logic of LSN capacity release.

**Comment by SSmallMonster** [comment]
Maybe it is the same root cause as https://github.com/hwameistor/hwameistor/issues/233

**Comment by SSmallMonster** [comment]
This is a screenshot of the comparison between the use capacity of LSN records and the actual LV use capacity in my cluster.

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/22465917/187054816-fdeffaad-88a9-4f34-9312-1128becb04a4.png">

It can be seen that many **LocalVolumes have actually been deleted, but they still exist in the LSN.**
