### ISSUE TITLE
The processing of the queue timed out, resulting in the capacity not being released in time

### ISSUE THREAD

**Issue by SSmallMonster** [hwameistor/hwameistor#236]
![image](https://user-images.githubusercontent.com/22465917/186612149-028236de-d0b7-4812-80b2-3b383ba0a2af.png)

The whole capacity release process is nearly 3 min.

**Comment by sun7927** [comment]
@FloatXD please test this case against the latest HwameiStor version.

**Comment by sun7927** [comment]
Deadline: August
