### ISSUE TITLE
Hwameistor Helm chart miss the values.schema.json file

### ISSUE THREAD

**Issue by Ye-Ting** [hwameistor/hwameistor#262]
HI team，

当前 Hwameistor Helm chart 内部没有 values.schema.json， 无法借助其形成可视化表单，能否加入该能力？ 

Output of `lsblk`:
```
# paste output here
```

Output of `blkid`:
```
# paste output here
```

Output of `kubectl version`:
```
# paste output here
```

Output of `kubectl get lsn -o yaml`:
```
# paste output here
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```

**Comment by SSmallMonster** [comment]
Hi @Ye-Ting , thanks for your feedback.

We will add a new values.schema.json file against value.yaml at next version.
