### ISSUE TITLE
Question about hwameistor-kube-scheduler must be scheduled to the master node

### ISSUE THREAD

**Issue by Ye-Ting** [hwameistor/hwameistor#263]
Hi Hwamei Team

默认的 helm 的模版中， hwameistor-kube-scheduler  采用了 `requiredDuringSchedulingIgnoredDuringExecution ` 来强制指定调度到 Kubernetes master 节点，这个是什么样的设计原因？ 

是否可以采用 `preferredDuringSchedulingIgnoredDuringExecution ` 会更加合理？

**Comment by Ye-Ting** [comment]
我实验如下pei zh配置是成功的，供参考
![image](https://user-images.githubusercontent.com/8576059/188113265-aa786df1-5da8-4fa7-aafa-ed5f0bcbdc58.png)

**Comment by SSmallMonster** [comment]
Thanks for your suggestions and contribution.
