### ISSUE TITLE
hwameistor scheduler can not be deployed in  control-plane when the cluster is deployed by kubean 

### ISSUE THREAD

**Issue by qiupingdai** [hwameistor/hwameistor#266]
hwameistor scheduler can not be deployed in  control-plane when the cluster is deployed by kubean 
because the control plane without the label "node-role.kubernetes.io/master :

<img width="1003" alt="企业微信截图_c95eff5b-f918-406b-90bd-43ee042c4573" src="https://user-images.githubusercontent.com/51350338/188123053-58c30bf0-9f8b-407e-8181-92a55eb4e206.png">

**Comment by SSmallMonster** [comment]
fixed in https://github.com/hwameistor/hwameistor/pull/283
