### ISSUE TITLE
/etc/hosts and hostname are inconsistent, causing drbd to fail to run properly

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#282]
![图片](https://user-images.githubusercontent.com/76234281/188557294-20bc0184-058f-4717-8ea5-05a1abbb94dd.png)

**Comment by qiupingdai** [comment]
high

**Comment by SSmallMonster** [comment]
fix at: https://github.com/hwameistor/drbd-adapter/pull/20
