### ISSUE TITLE
[Proposal] Support for LVM thin provision

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#360]
thin provision is very useful.

- Storage space can be used more effectively. More users can be accommodated for the same amount of storage space when compared to thick provisioning. This significantly reduces upfront hardware cost for the storage admins.
- Faster clones and snapshots.

We can consider to support

ref to https://github.com/topolvm/topolvm/blob/main/docs/proposals/thin-volumes.md

**Comment by SSmallMonster** [comment]
@yankay 
Thanks for your proposal. 

Now, **LVM Thin Provision** has been added in `Roadmap`.
