### ISSUE TITLE
[Proposal] Support Loop Device for Demo

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#381]
Loop Device is easy to demo

ref to https://github.com/topolvm/topolvm/blob/main/example/Makefile#L91

**Comment by yankay** [comment]
remind

**Comment by zhaosimon** [comment]
to be discuss

**Comment by sun7927** [comment]
loop device is not a best choice for HwameiStor demo, as that lots of features can't work for loop device, such as disk health monitoring, disk discovery, etc ...

For demo, it's easy to add a disk into a VM, which is better.

**Comment by panpan0000** [comment]
even not full function can be demo, but at least it can running inside kind. Yes,  it's worth only when it's not a big effort , of coz.
