### ISSUE TITLE
[Discussion] Ignore the webhook for the kube-system

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#390]
The same as:

https://github.com/topolvm/topolvm/pull/430

**Comment by SSmallMonster** [comment]
Hi, @yankay 

Yes, we should exclude hook calls from the `kube-system` namespace.

I think a better way is to use the specified key for exclusion(e.x. hwameistor.io/webhook).

>The problem is that users must manually operate and maintain such keys. We can ensure that at least the Release NameSpace can be automatically labeled with such key.

I will improve the logic of this part in the near future.

Thanks for your suggestions.
