### ISSUE TITLE
Add Notes in helm install

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#4]
When we use helm to install hwameistor.  It shows:

![企业微信截图_165527348318](https://user-images.githubusercontent.com/1469319/173755420-9f6bd4ae-3511-41ae-9784-2aa33dee61b2.png)

The user cannot know whether the install is success or fail.

Show we add Notes in helm like bitnami (https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/NOTES.txt)
Give the use some suggestion to check the install.

**Comment by niulechuan** [comment]
Yes, it's a great suggestion.
