### ISSUE TITLE
about release note

### ISSUE THREAD

**Issue by SAMZONG** [hwameistor/hwameistor#422]
maybe we need more details

Thanks you guys making great project

**Comment by SSmallMonster** [comment]
@SAMZONG 

We now use [release-process](https://github.com/hwameistor/hwameistor/blob/main/release-process.md) to release version.

You can find Release Notes about any version by searching `Release Proposal` in [issues](https://github.com/hwameistor/hwameistor/issues)(e.x. [Release Proposal v0.4.0](https://github.com/hwameistor/hwameistor/issues/411)).

If you have any suggestions about release-process or any confusion about one 
special version release, please leave a comment :-)

Thanks for your feedback, let's make it better.

**Comment by SAMZONG** [comment]
@SSmallMonster This great!

maybe just do a small things, add `Release Proposal` Issue link with github action jobs.

it's will helpful watcher, Know what happened with new release in GITHUB feed dashboard

![CleanShot 2022-10-27 at 10 40 53](https://user-images.githubusercontent.com/13782141/198178105-dcee38e1-8dcb-498f-a042-909e339878da.jpg)


> good sample.
![CleanShot 2022-10-27 at 10 37 38](https://user-images.githubusercontent.com/13782141/198177841-3a66e2fc-3e1e-4c26-9eb5-0a9522e74ffe.jpg)

**Comment by SSmallMonster** [comment]
@SAMZONG Good!

We have add release notes for release v0.4.0. In the future, the content on both sides will be synchronized.
