### ISSUE TITLE
Disucussion: change scheduler-name in deployment yaml is not easy to use

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#45]
Change scheduler-name in deployment yaml is not easy to use.

If user want to install wordpress from bitnami, he cannot run

```
helm install wp -n wp5 community/wordpress  --create-namespace
```

He should run:
```
helm install wp -n wp5 community/wordpress --set global.imageRegistry=docker.m.daocloud.io --set schedulerName=hwameistor-scheduler  --set mariadb.schedulerName=hwameistor-scheduler  --create-namespace
````

The config is very diffcult for user.

**Comment by SSmallMonster** [comment]
@yankay Thanks for your feedback

For now, we will add AdmissionController WebhookConfiguration to solve this question.
