### ISSUE TITLE
csi-node-driver-registrar is from k8s.gcr.io

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#46]
According to the docs : https://kubernetes-csi.github.io/docs/node-driver-registrar.html, csi-node-driver-registrar is from k8s.gcr.io. But the is from the https://github.com/hwameistor/helm-charts/blob/main/charts/hwameistor/values.yaml#L1, It's from the Quay.io .

**Comment by SSmallMonster** [comment]
We encountered a problem when modifying the image repository. The CSI node driver register image was migrated **from version [v2.0.0](https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.0.0) to `k8s.gcr. io`**, but the image has not been migrated **before(e.x. v1.1.0 we now use), and it still exists in `qury.io`**

If we upgrade the version directly, may face some compatibility problems, and we may need more tests.
