### ISSUE TITLE
Uninstall processes

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/hwameistor#48]
I could not find the uninstall processes in ReadMe, not sure if there is or not?

It is necessary sometimes to remove all the hwamei components completely for testing purpose.

**Comment by SSmallMonster** [comment]
@zhaosimon The system can be uninstalled through helm uninstall hwameistor. However, relevant resources will not be deleted. 

Therefore, if you want to delete them completely, you need to know whether the resources below are used by the upper application. This process may be more complex and cautious. 

After confirming that it is not used, you can delete the relevant resources (you can see the resource definition through kubectl API resources | grep hwameistor)
