### ISSUE TITLE
hwameistor-scheduler  crashloopbackoff

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#483]
v0.3.7-rc8
![图片](https://user-images.githubusercontent.com/76234281/203256120-95283e04-697b-4da6-83a0-2894952c2f6e.png)
v0.4.3
![图片](https://user-images.githubusercontent.com/76234281/203267754-f4571978-d815-470f-94c9-7574252ff96c.png)

**Comment by SSmallMonster** [comment]
@FloatXD 
Please checkout the scheduler-config version in cm. 

The correct configuration should be:
**v0.4.3**                 : `v1alpha1`
**v0.5.0 and later** : `v1beta1`
