### ISSUE TITLE
The node-role.kubernetes.io/master taint is deprecated and will be removed in kubeadm version 1.25

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#5]
The node-role.kubernetes.io/master taint is deprecated and will be removed in kubeadm version 1.25.

It would be replace by node-role.kubernetes.io/control-plane. like:
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/manifests/vanilla/vsphere-csi-driver.yaml#L220

**Comment by SSmallMonster** [comment]
@yankay Thanks for your suggestions.

We have noticed this problem, and we will fix this in the next release version.

**Comment by panpan0000** [comment]
duplicated with https://github.com/hwameistor/hwameistor/issues/230

**Comment by SSmallMonster** [comment]
fixed at:https://github.com/hwameistor/hwameistor/pull/281, https://github.com/hwameistor/hwameistor/pull/283
