### ISSUE TITLE
After hwameisto is successfully installed, pv cannot be created

### ISSUE THREAD

**Issue by WadeZeak** [hwameistor/hwameistor#521]
![企业微信截图_c11833d0-9f4f-4b4a-9acb-cb895e65f36e](https://user-images.githubusercontent.com/25677767/205419505-0fe83ab6-378b-4915-92bf-bee2d30a260d.png)
![企业微信截图_0f60ca93-90ec-4755-8118-014bae5711e1](https://user-images.githubusercontent.com/25677767/205419510-f8b00a95-dbf0-4c34-a668-1b12c3f02993.png)
![企业微信截图_114b9140-ffb9-4a5e-b9ef-3a29dd75c685](https://user-images.githubusercontent.com/25677767/205419514-fa6ac738-6869-4c49-a0e9-91ac86558642.png)
After the hwameistor storage is successfully installed, pvc is created, but pv cannot be created automatically, and it prompts to wait for pod scheduling

**Comment by SSmallMonster** [comment]
@WadeZeak 
Can you try again after removing `kubeconfig` in SchedulerConfig and Deploy?

Ref: #520
