### ISSUE TITLE
SSD disks are not claimed after installing

### ISSUE THREAD

**Issue by buffalo1024** [hwameistor/hwameistor#534]
Output of `kubectl get lsn -o yaml`:

![image](https://user-images.githubusercontent.com/49835372/206382593-7c300dc4-28b0-4de3-9be2-4cf1ef8e8648.png)

storageClass:

![image](https://user-images.githubusercontent.com/49835372/206382815-b8e38524-9499-4c7f-89ff-3153e16e2fcf.png)

localDisks:

![image](https://user-images.githubusercontent.com/49835372/206382959-6219934e-f785-4469-9e29-38f7e3205351.png)

**Comment by SSmallMonster** [comment]
@buffalo1024 Can you show LocalDiskClaim info?
