### ISSUE TITLE
[Feature Request] [LOW Priority] show PV capacity usage in some CRD?

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#555]
currently, when a PV is filled up, there's no way to realize it.

We have to  rely on  `df` on the node , or rely on node-exporter of kubelet metrics.

sometimes to business system, when PV is filled up , if below can be achieve , it will be awesome.
- a timely alert (prometheus + kubelet can help)
- **auto** scale up (or semi-automation) the pvc  🎉

because storage is cheap, business is valuable.

It's said that longhorn having this kind of sizing monitor feature. maybe a reference.

@sun7927 @SSmallMonster @yankay

**Comment by SSmallMonster** [comment]
See [Longhorn Capacity Monitoring](https://longhorn.io/img/screenshots/monitoring/longhorn-example-grafana-dashboard.png)

It seems good to collect VolumeUsage metrics in our metrics components(incoming `v0.7.0`).

**Comment by sun7927** [comment]
hwameistor metrics feature will include it. And volume auto-expansion is on the plan.
