### ISSUE TITLE
hwameistor can't provide PV

### ISSUE THREAD

**Issue by cqmmm** [hwameistor/hwameistor#560]
I use 0.3.29 dce-installer to install DCE 5.0, when mysql-operator needs persistent volumes. hwameistor can't provide PV.
scheduler logs：
<img width="1440" alt="WeChatWorkScreenshot_3b722b59-b2aa-4d08-a15f-d5149f83c72a" src="https://user-images.githubusercontent.com/74850217/209049855-6b368b8c-1894-4907-9ed1-e9b6390f8c6d.png">

**Comment by SSmallMonster** [comment]
@cqmmm Thanks for your feedback.

This is a known issue, https://github.com/hwameistor/hwameistor/pull/520 is solution.
