### ISSUE TITLE
Scheduler ,Controller has only one replica ,when Node out of service ,Hwameistor will does not work 

### ISSUE THREAD

**Issue by qiupingdai** [hwameistor/hwameistor#579]
from zhenguang: 
Scheduler ,Controller has only one replica ,when Node out of service ,Hwameistor will does not work

**Comment by zhaosimon** [comment]
Kubernetes has its own scheduler and controller, however, Hwameistor can also provide HA provisioning.

**Comment by zhaosimon** [comment]
HwameiStor currently support HA provisioning.  number of replicas can be configured with helm value.
