### ISSUE TITLE
Can't Bound Free Disks

### ISSUE THREAD

**Issue by gssjl2008** [hwameistor/hwameistor#582]
Output of `lsblk`:
```
# paste output here
```
<img width="282" alt="企业微信截图_5e48f043-fa9c-4d12-98ac-e9e0791c5a4a" src="https://user-images.githubusercontent.com/43020699/210294593-c50f6c5f-b947-45d1-b35a-ba5ace7a6e44.png">

Output of `blkid`:
```
# paste output here
```

Output of `kubectl version`:
```
# paste output here
```
<img width="479" alt="企业微信截图_6e148385-5c0a-4caf-b895-19d29da27a04" src="https://user-images.githubusercontent.com/43020699/210294516-af22952f-a931-4db1-b522-3dbda0e7213b.png">

Output of `kubectl get lsn -o yaml`:
```
# paste output here
```
<img width="1136" alt="企业微信截图_6d3b8b36-1e0c-46be-8d6e-f866efb2564f" src="https://user-images.githubusercontent.com/43020699/210294563-19b040f1-5af1-4a0e-ba74-74aedfa6eeca.png">

裸盘有空余，但是无法 claim ，

**Comment by SSmallMonster** [comment]
@gssjl2008 Thanks for your feedback, this problem was fixed in v0.6.1, please update and retry.
