### ISSUE TITLE
硬件配置规划的最佳实践是什么

### ISSUE THREAD

**Issue by timorsea** [hwameistor/hwameistor#587]
请问生产环境下裸机部署时硬件配置的最佳实践：

1. 系统盘、数据盘的数量、类型、容量的不同选择，raid的配置建议；
2. 网络配置建议：生产网、管理网、存储网等如何融合或分离，千兆、万兆网卡如何配置；

**Comment by sun7927** [comment]
生产环境下的建议如下：

系统盘：2块SSD，做RAID#1，互为保护，每块盘容量 >= 500GB
数据盘：
   1. 大容量：6块HDD(例如：单块容量 2TB)，做RAID#5，5:1 保护，可用容量 10TB。单块容量越大，磁盘rebuild时间越长。
   2. 高访问速度：4块SSD，做RAID#4（3:1保护）；或者6块SSD，做RAID#5（5:1）保护。RAID#4获得的性能更优。
   3. 极速访问：NVMe SSD，不做RAID保护（成本高，影响性能）
 
网络配置建议
生产网络和管理网络：和Kubernetes集群的生产网络一致。应用Pod访问本地数据卷，不通过网络。
存储网络：每个存储节点上单独一块网卡，组成独立的网络，用于HA数据卷的数据同步。
