### ISSUE TITLE
Balanced Scheduling Volumes

### ISSUE THREAD

**Issue by gssjl2008** [hwameistor/hwameistor#589]
At the time of creation, there are a total of 5 nodes, of which 4 nodes are zoned, resulting in only one node claimed
The pv created later is all scheduled to the same node. When the capacity is small, the container goes online, and the capacity cannot be expanded at this time.
How to reschedule the allocated storage, hoping to add this function

**Comment by sun7927** [comment]
volume migration feature can help with it, please check https://hwameistor.io/docs/quick_start/create_stateful/advanced/migrate for details

**Comment by SSmallMonster** [comment]
Balanced Volumes Scheduling is supported at version `v0.7.2`.
