### ISSUE TITLE
ssd type disk unclaimed after installing

### ISSUE THREAD

**Issue by buffalo1024** [hwameistor/hwameistor#590]
![image](https://user-images.githubusercontent.com/49835372/210552310-ba8cb074-24b4-4f71-adcc-c9244c771618.png)

![image](https://user-images.githubusercontent.com/49835372/210552437-a91a12bb-5f1f-48cc-b432-8e80256bafb6.png)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```

**Comment by SSmallMonster** [comment]
@buffalo1024 What's the hwameistor version, and have you apply any ldc?

```shell
$ kubectl get ldc 
```

**Comment by zhaosimon** [comment]
operator can solve this issue, in testing
