### ISSUE TITLE
hwameistor helm chart schema is not proper

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#594]
when DRBD is disable, the below two parameter(DRBDStartPort ...etc ) should not appear :

when delete the two parameter in yaml, helm validation pass.

![image](https://user-images.githubusercontent.com/14049268/210773628-1d1f8e30-8d6c-4d9c-a0cc-f7f1b0d6f536.png)

**Comment by SSmallMonster** [comment]
@angel0507 take a look~

**Comment by zhaosimon** [comment]
update to the lastest version, problem solved
