### ISSUE TITLE
Discussion: Should we use config instead of the "node label"

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#6]
When we install the hwamei stor, the user must to use "node label" to select the node enabled

Should we change it to the config file , like  https://github.com/rancher/local-path-provisioner#configuration

Benifit:
1. The config can be declared in the helm values.
2. We can use "auto policy" in config file, like " all free disk" , so that the use donot need to write the config mannaly. 
3. Remove the Step in Installtion to make install simpler

**Comment by SSmallMonster** [comment]
@yankay Thanks for your suggestion, 

>When we install the hwamei stor, the user must to use "node label" to select the node enabled

We realize that this operation brings some complexity to the user experience.

>Should we change it to the config file , like https://github.com/rancher/local-path-provisioner#configuration

As for the config file method you mentioned, we will consider it in the subsequent discussion and optimization.
