### ISSUE TITLE
Disk Status Monitor ready or not?

### ISSUE THREAD

**Issue by qiupingdai** [hwameistor/hwameistor#612]
When the disk failed ，Is Hwameistor can be monitored or not?

**Comment by qiupingdai** [comment]
1. when it is Physical disk，the SMART  info can be collected ,and with dashboard such as grafana，the status can be viewed 
2. when it is Raid，the function is developing，Q1~Q2 can be ready

**Comment by SSmallMonster** [comment]
Disk health monitor is ready now, metrics of disk health info are exposed now.
