### ISSUE TITLE
Enhancement：Add support for expanding existing device

### ISSUE THREAD

**Issue by tishaluo** [hwameistor/hwameistor#617]
When the existing device in the storage pool has been expanded, hwameistor can not recognize the new size.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
CCE
```

**Comment by SSmallMonster** [comment]
@tishaluo Thanks for your feedback.

We should indeed be able to correctly update the underlying storage capacity when modifying the disk capacity directly.

We will fix it in next version.

**Comment by SSmallMonster** [comment]
This problem will be fixed in https://github.com/hwameistor/hwameistor/pull/618
