### ISSUE TITLE
The storage can be used normally, but the LDC status is "pending"

### ISSUE THREAD

**Issue by zizhufanqing** [hwameistor/hwameistor#664]
# kubectl get ldc
NAME                NODEMATCH           PHASE
controller-node-1   controller-node-1   Pending
node-1              controller-node-1   Pending
node-2              worker-node-1       Pending
node-3              worker-node-2       Pending
worker-node-1       worker-node-1       Pending
worker-node-2       worker-node-2       Pending

The disk is SDD, but the HDD is issued, so the LDC is recreated through YAML，Node-1, node-2 and node-3 are the LDC of SSDs created through YAML，And because the SC created is HHD by default, it is recreated through YAML as the type of SSD
# kubectl describe ldc node-1
Name:         node-1
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  hwameistor.io/v1alpha1
Kind:         LocalDiskClaim
Metadata:
  Creation Timestamp:  2023-02-28T02:23:31Z
  Generation:          1
  Managed Fields:
    API Version:  hwameistor.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:description:
          .:
          f:diskType:
        f:nodeName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-02-28T02:23:31Z
    API Version:  hwameistor.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:status:
    Manager:         local-disk-manager
    Operation:       Update
    Subresource:     status
    Time:            2023-02-28T02:23:31Z
  Resource Version:  216654
  UID:               951fd045-982b-47fe-bf3b-73cbab1a705d
Spec:
  Description:
    Disk Type:  SSD
  Node Name:    controller-node-1
Status:
  Status:  Pending
Events:    <none>

# kubectl get pvc
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
task-pv-claim   Bound    pvc-6231892a-dcbd-4288-8fde-21b5ab90c75c   3Gi        RWO            local-storage-ssd-lvm   64m

**Comment by zhaosimon** [comment]
can you provide 'lsn', 'ld' status and yaml configuration?

**Comment by zhaosimon** [comment]
no response, close!
