### ISSUE TITLE
Failed to expand storage capacity, err: exit status 1

### ISSUE THREAD

**Issue by amazingpnc** [hwameistor/hwameistor#685]
Output of `lsblk`:
```
# paste output here
```

Output of `blkid`:
```
# paste output here
```

Output of `kubectl version`:
```
# paste output here
```

Output of `kubectl get lsn -o yaml`:
```
# paste output here
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```

**Comment by amazingpnc** [comment]
root@zyliang-master:~# kubectl get lsn zyliang-master2 -o yaml
apiVersion: hwameistor.io/v1alpha1
kind: LocalStorageNode
metadata:
  creationTimestamp: "2023-02-14T13:24:53Z"
  generation: 1
  name: zyliang-master2
  resourceVersion: "31133686"
  uid: 8b49974b-45ce-4291-b8e9-af47a13696fb
spec:
  hostname: zyliang-master2
  storageIP: 10.182.218.202
  topogoly:
    region: default
    zone: default
status:
  conditions:
  - lastTransitionTime: "2023-03-14T08:27:24Z"
    lastUpdateTime: "2023-03-14T08:27:24Z"
    message: 'Failed to expand storage capacity, err: exit status 1'
    reason: StorageExpandFailure
    status: "True"
    type: StorageExpandFailure
  - lastTransitionTime: "2023-03-14T08:27:41Z"
    lastUpdateTime: "2023-03-14T08:27:41Z"
    message: Successfully to expand storage capacity
    reason: StorageExpandSuccess
    status: "True"
    type: StorageExpandSuccess

**Comment by FloatXD** [comment]
![图片](https://user-images.githubusercontent.com/76234281/224951609-1ccee3d5-5ffc-4bb7-8a89-2fb70da0358b.png)

**Comment by FloatXD** [comment]
The error caused by the node not installing LVM
