### ISSUE TITLE
Readme about Release Status needs update

### ISSUE THREAD

**Issue by Penguin-zlh** [hwameistor/hwameistor#686]
Latest version is v0.8.0. But it is displayed as v0.7.2 in readme
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/57695165/224957468-5dcbc0e2-b937-4c9f-b3be-dffc0ebcfee7.png">
<img width="206" alt="image" src="https://user-images.githubusercontent.com/57695165/224957558-96a53292-55f7-4226-b267-b4f1eee93830.png">

**Comment by zhaosimon** [comment]
fixed！
