### ISSUE TITLE
Can not delete lvconvert by command 'kubectl delete lvconvert xxx'

### ISSUE THREAD

**Issue by Penguin-zlh** [hwameistor/hwameistor#689]
## Description
Can not delete lvconvert by command 'kubectl delete lvconvert xxx'

## Step
before delete
![image](https://user-images.githubusercontent.com/57695165/225193241-c5329c5a-e038-46c0-800a-621d6b8a94a4.png)

after delete. It will be recreated
![image](https://user-images.githubusercontent.com/57695165/225193303-035c7e16-c537-4f73-a44f-e53f28d0d07a.png)

## Expect
Can delete lvconvert successfully by command 'kubectl delete lvconvert xxx'

**Comment by sun7927** [comment]
The correct way to delete lvconvert is to set spec.abort=true. otherwise, it can't be deleted. it's expected by design.

**Comment by zhaosimon** [comment]
no response from user, close!
