### ISSUE TITLE
failed while expanding pvc

### ISSUE THREAD

**Issue by amazingpnc** [hwameistor/hwameistor#702]
zyliang-worker2 kubelet[9465]: E0317 13:55:28.144305    9465 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/lvm.hwameistor.io^pvc-6fae3dae-386e-42e0-bf41-b28d329626c8 podName: nodeName:}" failed. No retries permitted until 2023-03-17 13:57:30.144276591 +0800 CST m=+2750108.522417022 (durationBeforeRetry 2m2s). Error: MountVolume.Setup failed while expanding volume for volume "pvc-6fae3dae-386e-42e0-bf41-b28d329626c8" (UniqueName: "kubernetes.io/csi/lvm.hwameistor.io^pvc-6fae3dae-386e-42e0-bf41-b28d329626c8") pod "mcamel-common-es-cluster-masters-es-masters-1" (UID: "195cc26b-8e25-454f-b5df-adf8bacadff8") : Expander.NodeExpand failed to expand the volume : rpc error: code = Unknown desc = exit status 1

**Comment by FloatXD** [comment]
![图片](https://user-images.githubusercontent.com/76234281/225824589-15364aeb-4a7a-4ec3-ab32-cae5d2bdcf13.png)
Need to install xfsprogs
