### ISSUE TITLE
Docs: Improve kubectl command 

### ISSUE THREAD

**Issue by mengjiao-liu** [hwameistor/hwameistor#703]
Page: https://hwameistor.io/docs/quick_start/advanced_features/node_expansion#post-check

The  `kubectl get localstoragenode k8s-worker-4` command should have `-o yaml` appended at the end.
The correct command would be:
```
kubectl get localstoragenode k8s-worker-4 -o yaml
```

This problem exists in both the Chinese version and the English version. Please check.

/kind bug

**Comment by zhaosimon** [comment]
thanks，could you please submit a pr for this fix?

**Comment by mengjiao-liu** [comment]
> 

Okay. I will submit a PR to fix it.

**Comment by zhaosimon** [comment]
any advice for HwameiStor are very welcome, include architect, features, code, docs.!

**Comment by mengjiao-liu** [comment]
By the way, I haven't submitted PR in this repo before, since this issue exists in both Chinese and English, can I modify both languages in one PR?

**Comment by mengjiao-liu** [comment]
Here is the fixed PR: https://github.com/hwameistor/hwameistor/pull/706
