### ISSUE TITLE
Clarify the 'Eviction' attribute in the Advanced Feature

### ISSUE THREAD

**Issue by yanzhifa** [hwameistor/hwameistor#721]
https://hwameistor.io/docs/quick_start/advanced_features/volume_eviction

Could I clarify the 'Eviction' attribute in the Advanced Feature above:  after I went through the description and steps, what the hwameistor is doing is just a data volume migration, while the node/pod evictions are kubernetes native?

**Comment by zhaosimon** [comment]
yes, you are right! Node-pressure eviction is the process by which the kubelet proactively terminates pods to reclaim resources on nodes, however, HwameiStor can sense the eviction and automatically migrate them to other avaliable nodes.
