### ISSUE TITLE
Volume Eviction failed

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#722]
![图片](https://user-images.githubusercontent.com/76234281/227121808-4a1e4827-fdef-457b-b61b-f62941325fa4.png)

**Comment by zhaosimon** [comment]
interesting issue, is this a eviction testing, can you share the whole steps?

**Comment by FloatXD** [comment]
> interesting issue, is this a eviction testing, can you share the whole steps?有趣的问题，这是一个驱逐测试，你能分享整个步骤吗？
1. kubectl drain
2. hwameistor will detect the data volumes mounted on the sts workloads, and migrate to the assigned nodes using rclone or drbd 
3. after migration, pod scheduled and mount the new volumes

**Comment by FloatXD** [comment]
fix in https://github.com/hwameistor/hwameistor/pull/724

**Comment by zhaosimon** [comment]
so what is the problem?
