### ISSUE TITLE
LocalDisk (ld) status error of disk type StorageClass

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/hwameistor#755]
I created a disk type storageClass with the 2 disks of sdd.  One of them bound to a app, but the ld status showing 'available' not 'bound'

<img width="1216" alt="屏幕快照 2023-03-29 下午3 42 43" src="https://user-images.githubusercontent.com/36882380/228462190-44c69d1b-6ca4-4222-9231-79da1ca966e7.png">

**Comment by SSmallMonster** [comment]
fix at next version.

**Comment by zhaosimon** [comment]
thanks！
