### ISSUE TITLE
Simulated a node failure,  second replica lvr is failed to mount to the migrated po.

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/hwameistor#766]
I made the 24 node 'not ready' by 'systemctl stop kubelet'.

2 replicas of lvr
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/36882380/229698049-1038ae29-1c96-40f8-956e-0a7177eccc74.png">

pod migrated from 24 to 22
<img width="1245" alt="屏幕快照 2023-04-04 下午12 12 36" src="https://user-images.githubusercontent.com/36882380/229697810-0741fe89-4b3c-407f-af22-6a3c1b2531af.png">

volume mount failed
<img width="1254" alt="屏幕快照 2023-04-04 下午1 32 41" src="https://user-images.githubusercontent.com/36882380/229697823-13eeea88-65ed-4559-a105-96db99f5f459.png">

**Comment by zhaosimon** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/36882380/229701127-5887c71b-7524-44e1-9fe4-ee6374f4ee34.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/36882380/229701224-526f2bcd-58a5-4414-a207-154a3e24d5b8.png">

**Comment by zhaosimon** [comment]
shutdown the 24 node
<img width="369" alt="屏幕快照 2023-04-04 下午2 13 49" src="https://user-images.githubusercontent.com/36882380/229703641-3427ab8a-3614-4492-b2c1-60d1d226eac7.png">

drbd status changed
<img width="492" alt="屏幕快照 2023-04-04 下午2 13 33" src="https://user-images.githubusercontent.com/36882380/229703727-ba7c37ae-9e44-451a-94bd-828524e428f4.png">

pod running
<img width="571" alt="屏幕快照 2023-04-04 下午2 13 07" src="https://user-images.githubusercontent.com/36882380/229703807-eee9d600-ba95-4a95-b097-02737de71c37.png">

**Comment by FloatXD** [comment]
In the high-availability scenario, the drbd primary and secondary are not switched

**Comment by SSmallMonster** [comment]
If `kubelet` stopped, there is no effect on drbd and pod, so the new pod will failed at `MountVolume` stage. 

When node is offline, drbd change its connection status, so the new pod will run successfully.

Both of this 2 results meet our expectations.

**Comment by zhaosimon** [comment]
The problem is when kubelet stopped, the pod failed over to another node, but the volume mount failed
