### ISSUE TITLE
hwamei can’t recognize SSD disk normally, non-NVME solid state will be recognized as HDD

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#767]
![图片](https://user-images.githubusercontent.com/76234281/229708515-037c7b94-cf48-4fa7-ab01-4531e9ac6d44.png)
![图片](https://user-images.githubusercontent.com/76234281/229708535-58d19d11-df4f-422e-9fda-b13e7db8974d.png)

**Comment by zhaosimon** [comment]
is this test on physical machine, not VM?
