### ISSUE TITLE
The Disk Type in VM is NVMe ,but it display as “HDD” in hwameistor LDC

### ISSUE THREAD

**Issue by qiupingdai** [hwameistor/hwameistor#770]
The Disk Type in VM is NVMe ,but it display as “HDD” in hwameistor LDC
![wecom-temp-30643-a573d289793d59409e3e0ca4e43f4482](https://user-images.githubusercontent.com/51350338/229740940-0e41a640-3f85-4b7a-bd7a-976d90500a87.png)
![wecom-temp-68239-c1e2cdd09c5277b21f321cfaf352375b](https://user-images.githubusercontent.com/51350338/229740984-e26acfb0-c836-4bc8-a00d-4e917eb69f79.png)
![wecom-temp-28977-88f1c64c1986f314a4fbc21d927acb58](https://user-images.githubusercontent.com/51350338/229741055-284b1bf9-dc66-48bc-b55b-1fbe2b9e4d88.png)

**Comment by qiupingdai** [comment]
`kubectl edit ldc xxx` to correct it

**Comment by SSmallMonster** [comment]
dup: https://github.com/hwameistor/hwameistor/issues/770
