### ISSUE TITLE
Metrics Port Listen to 0.0.0.0:8383 , may cause security issue.

### ISSUE THREAD

**Issue by yankay** [hwameistor/hwameistor#774]
Metrics Port Listen to 0.0.0.0:8383, which may cause a security issue.

It can be work with a `metrics service`, instead of host port.
Or do not use the host network.

**Comment by SSmallMonster** [comment]
@yankay Thanks for your feedback.

`hostNetwork` may not be necessary, we will test and degraded network mode at next version.
