### ISSUE TITLE
How to clean up the storage volume whose reclaimPolicy is Retain？

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#80]
sc  yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-disk-hdd-disk
provisioner: disk.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Retain
parameters:
  diskType: "HDD"

pvc yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-disk-pvc
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  storageClassName: local-disk-hdd-disk
  resources:
    requests:
      storage: 5Gi

I created a sc whose reclaimPolicy is Retain, and created the corresponding pvc mount deploy.
Then I deleted the deploy, pvc, but because the reclaimPolicy is Retain, the pv is not deleted.
At this time, how can I delete the used storage and release the corresponding local disk？

**Comment by SSmallMonster** [comment]
> Why storage volume won't be deleted

If reclaimpolicy in storageclass is **Retain**, the provision(hwameistor) will not delete PV after PVC is deleted.So, the storage volume created by hwameistor  which presents the PV will not be deleted too.

> How do i delete stoage volume?

1. You need delete LocalDiskVolume whose name starts with PV name manually
2. Check out if the disk has released, if not, release it by kubectl
```
kubectl label ld <unreleased_local_disk> disk.hwameistor.io/pvc:<pvc>-
```
