### ISSUE TITLE
An application bound to 2 PVCs will have problems when performing the convert operation

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#806]
![图片](https://user-images.githubusercontent.com/76234281/233247883-97e4843b-e320-4640-895b-4b2072bbe407.png)
Will convert to 2 different nodes

**Comment by zhaosimon** [comment]
2 lv from same pod, should be in same LVG group.

**Comment by zhaosimon** [comment]
APP on node 2 mount 2 lv, they should be in the same local volume group (lvg).  after converting to HA, the new replicas should be in the same node (node1 or master)
