### ISSUE TITLE
Migrating a local volume to a highly available version reports an error

### ISSUE THREAD

**Issue by sangy001** [hwameistor/hwameistor#816]
![image](https://user-images.githubusercontent.com/37102834/233816868-43351284-b410-49fc-9758-6c770472333f.png)

![image](https://user-images.githubusercontent.com/37102834/233816848-ffd97d7a-b488-4420-85f0-7cc13843d3c9.png)

**Comment by lsq645599166** [comment]
error message has shown in https://github.com/hwameistor/hwameistor-ui/pull/19

**Comment by zhaosimon** [comment]
https://github.com/hwameistor/hwameistor-ui/pull/19

**Comment by buffalo1024** [comment]
What is the specific err?I guess maybe the pod using the volume is still running.Have you stopped the workload before migrating?

**Comment by buffalo1024** [comment]
I found that migration is not allowed when the LocalVolume's publishedNodeName is not "",that's the reason migrations from node holding a second replica are prevented.The issue has been fixed in https://github.com/hwameistor/hwameistor/pull/829
