### ISSUE TITLE
nginx deployment one PVC can mount to multiple scaled Pods

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/hwameistor#820]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/36882380/233889254-ff70b566-ac38-4dd5-acb3-3b94b83150fa.png">

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/36882380/233889351-60e1022c-c950-44f8-b178-ac8128699c29.png">

**Comment by zhaosimon** [comment]
[root@k8s-10-6-162-21 ~]# kubectl exec -it nginx-local-storage-lvm-58789c84d4-828np -- sh
#

# pwd
/usr/local/share
# ls
ca-certificates  fonts	man
# echo This is test-1 > test1.html

# ls
ca-certificates  fonts	man  test1.html
# exit
[root@k8s-10-6-162-21 ~]#
[root@k8s-10-6-162-21 ~]# kubectl exec -it nginx-local-storage-lvm-58789c84d4-k4pqk --sh
error: unknown flag: --sh
See 'kubectl exec --help' for usage.
[root@k8s-10-6-162-21 ~]# kubectl exec -it nginx-local-storage-lvm-58789c84d4-k4pqk -- sh
# cd /usr/local
# ls
bin  etc  games  include  lib  man  sbin  share  src
# cd share
# ls
ca-certificates  fonts	man
# echo This is test-2 > test2.html
# ls
ca-certificates  fonts	man  test2.html
# cat test2.html
This is test-2
# ls
ca-certificates  fonts	man  test2.html
#

**Comment by SSmallMonster** [comment]
@zhaosimon 

The  volume provided by Hwameistor can be accessed by pods scheduled at the same node.  

More info see [RWO](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes-1).
