### ISSUE TITLE
[Feature Request] When the data volume is migrated to other nodes, maintain the original permissions

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#830]
When the data volume is migrated to other nodes, maintain the original permissions

Request comes from: https://github.com/hwameistor/hwameistor/issues/828

**Comment by zhaosimon** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/36882380/236365917-ad145a14-81c1-438d-844c-9428a872d515.png">
The permissions on dir & files should keep same under expectation.

**Comment by zhaosimon** [comment]
Permissions can be restored by APPs initContainers.

**Comment by panpan0000** [comment]
+1

**Comment by panpan0000** [comment]
disagree to close ...

**Comment by sun7927** [comment]
This issue should be resolved by the latest version.
