### ISSUE TITLE
 [Feature Enhancement] - Need a CRD to take record for HwameiStor volume operations (lvmigrate/convert/resize etc.)

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/hwameistor#836]
This is a Feature Enhancement link to the issue: https://github.com/hwameistor/hwameistor/issues/795

Curently there is no CRD to take record for HwameiStor volume operations (lvmigrate/convert/resize etc.).  We need one for both UI and backend.

**Comment by zhaosimon** [comment]
palnned

**Comment by sun7927** [comment]
solved by PR https://github.com/hwameistor/hwameistor/pull/1056
