### ISSUE TITLE
[doc]Documentation details need improvement

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#857]
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/0184d5a1-03ad-41f4-9d95-fcc0e1d47b4c)

**Comment by zhaosimon** [comment]
fixing

**Comment by zhaosimon** [comment]
fixed at https://github.com/hwameistor/hwameistor/pull/863#issuecomment-1549335818
