### ISSUE TITLE
resizer with drbd failed 

### ISSUE THREAD

**Issue by panpan0000** [hwameistor/hwameistor#902]
The PVC increase from 50G to 90G, 

![企业微信截图_1686024806181](https://github.com/hwameistor/hwameistor/assets/14049268/fc781f02-944c-42ee-855a-cf6d97a870a4)

but drdb still 50G
![企业微信截图_16860248219117](https://github.com/hwameistor/hwameistor/assets/14049268/9b755bd4-14d9-4a91-9e8b-07e39186b519)

from mingming talk offline:
```
从这个结果看，hwameistor 对lv的扩容已经成功了，但是文件系统的扩容看起来没有成功。这部分的扩容是由kubelet 和 csi-resize 一起完成的，看了kubelet 和 resizer 的日志，没找到相关信息（因为POD间歇性连不上apiserver，重启次数很多，日志也没有太多）。 我们持续跟进这个问题吧。
resizer:
https://github.com/kubernetes-csi/external-resizer/blob/882049909bc94434f1199776980912dbb5b3e9b8/pkg/controller/controller.go#L411

kubelet:
https://github.com/kubernetes/kubernetes/blob/4ce5a8954017644c5420bae81d72b09b735c21f0/pkg/kubelet/volumemanager/reconciler/reconciler.go#L216
```

**Comment by zhaosimon** [comment]
<img width="1025" alt="屏幕快照 2023-06-21 上午11 01 15" src="https://github.com/hwameistor/hwameistor/assets/36882380/b4c24c2a-b4cd-430e-8a2f-392aa614cc56">
<img width="1029" alt="屏幕快照 2023-06-21 上午11 01 28" src="https://github.com/hwameistor/hwameistor/assets/36882380/3fa72396-d7e3-4829-8878-6e824c265580">
<img width="998" alt="屏幕快照 2023-06-21 上午11 01 49" src="https://github.com/hwameistor/hwameistor/assets/36882380/826b58e7-ba6e-4c65-bdd8-1dfd74ee66dd">

pvc 2G 改 3G， 22节点挂载的drbd卷是3G，但24节点的drbd卷还是2G

**Comment by zhaosimon** [comment]
This is not the case, we need recurring evidence.
