### ISSUE TITLE
安装 hwameistor 发现 sdb 磁盘未创建 pv, vg, 无可用容量

### ISSUE THREAD

**Issue by Archimedes-Dear** [hwameistor/hwameistor#903]
Output of `lsblk`:
![image](https://github.com/hwameistor/hwameistor/assets/17512365/34935893-e982-4907-8575-ef87ee86346d)

Output of `blkid`:
![image](https://github.com/hwameistor/hwameistor/assets/17512365/025f7625-e8b6-423f-be9b-00da98409048)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
DCE 5.0 
```

local-storage logs:
![image](https://github.com/hwameistor/hwameistor/assets/17512365/59d99c2d-68f9-46dd-88b2-2a35e067fd33)

**Comment by FloatXD** [comment]
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/0b9dff51-82c4-4cdc-91b1-47f205e18393)
The disk has GPT partition information, use the command to clean up the disk: wipefs -a /dev/sdb, and finally restart local-storage.

**Comment by SSmallMonster** [comment]
a GPT partition exist on disk may cause failure when `vgcreate`, the LocalDisk object should show `Bound` status.

i think we should fix this.

**Comment by sun7927** [comment]
one suggestion: when discover a disk, check if there is any partition on the disk, if yes, mark the disk/LD as unavailable with the reason. After clean up it manually, make it available then.
