### ISSUE TITLE
deleted pvc still showed at hwamei ui

### ISSUE THREAD

**Issue by liyuerich** [hwameistor/hwameistor#904]
1  create sc, pvc and deployment

2 delete sc, pvc and deployment created at step 1

3 check hwamei-UI, there is lagacy pvc( created at step 1)

suppose this pvc should not be displayed in UI

Output of `lsblk`:

NAME            MAJ:MIN   RM   SIZE RO TYPE MOUNTPOINT
sda               8:0      0   200G  0 disk 
├─sda1            8:1      0     1G  0 part /boot
└─sda2            8:2      0   199G  0 part 
  ├─centos-root 253:0      0    50G  0 lvm  /
  ├─centos-swap 253:1      0   7.9G  0 lvm  
  └─centos-home 253:2      0 141.1G  0 lvm  /home
sdb               8:16     0    50G  0 disk 
├─LocalStorage_PoolHDD-pvc--99bdfa30--d547--4614--8e97--b17dbee38902
                253:3      0    10G  0 lvm  
│ └─drbd43001   147:43001  0    10G  0 disk 
└─LocalStorage_PoolHDD-pvc--d57e876d--29ad--4455--8fb6--4cc417e5403e
                253:4      0    10G  0 lvm  /var/lib/kubelet/pods/78a9f835-9a13-43a0-8d83-cb11498bacd8/volumes/kubernetes.io~csi/pvc-d5
sr0              11:0      1  1024M  0 rom 

Output of `blkid`:
```
# dev/sda1: UUID="b5603063-3e30-4a8d-a83f-acd19a582041" TYPE="xfs" 
/dev/sda2: UUID="MToCjf-qptN-EbMB-J8hT-YJnu-Vm67-BzPIei" TYPE="LVM2_member" 
/dev/mapper/centos-root: UUID="5ab6b56e-4c4e-4b11-b8eb-c91a8cce91a4" TYPE="xfs" 
/dev/mapper/centos-swap: UUID="2f8faeba-6ebf-47e2-9c1d-1b79abb432fa" TYPE="swap" 
/dev/mapper/centos-home: UUID="56f84b2c-90a5-489f-a8b4-bc9506e56043" TYPE="xfs" 
/dev/sdb: UUID="3EsMBJ-VSZN-7BBN-OgO9-aGKg-fZCT-uiBpsq" TYPE="LVM2_member" 
/dev/drbd43001: UUID="66543e10-6ea1-495d-96cd-2520718e6f36" TYPE="xfs" 
/dev/mapper/LocalStorage_PoolHDD-pvc--d57e876d--29ad--4455--8fb6--4cc417e5403e: UUID="3e939e73-6ad0-416b-906e-495732a1bfe2" TYPE="xfs" 

```

Output of `kubectl version`:
```
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Output of `kubectl get lsn -o yaml`:
```
# paste output here
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```

**Comment by zhaosimon** [comment]
how about kubectl get pvc/pv?
