### ISSUE TITLE
ha pvc pending 

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#926]
pod pending && pvc pending ， pv and lv are not created
pod events
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/451195cd-1495-473b-87fb-a1080c2340a3)
scheduler log
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/31e77959-5d32-48ee-b093-a7f2e9e1f8fb)
view lease
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/7a333bf6-91cb-4259-a9c6-161dd6bb79dc)
View local-storage logs on node03
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/66b6c2bd-8f6e-446d-ac30-0441f3a2153a)
Judgment is caused by drbd status error on redis02
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/07aa9582-2dad-4cb2-87ce-e9e8fd2ddca7)
![图片](https://github.com/hwameistor/hwameistor/assets/76234281/c97e3ce4-edad-4434-a7bd-152f55a5cfa2)

**Comment by zhaosimon** [comment]
Customer site problem, resolved.  suppose caused by drbd problem
