### ISSUE TITLE
Applications cannot be scheduled normally in a namespace other than hwameistor

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#93]
![图片](https://user-images.githubusercontent.com/76234281/181417828-f2a16eda-3d48-4566-a099-925dbc55369c.png)

![图片](https://user-images.githubusercontent.com/76234281/181417791-6bbae321-43d7-4c3c-8f65-0be17e763cd8.png)
![图片](https://user-images.githubusercontent.com/76234281/181417807-c4dc53ac-c4e5-4130-a3f8-8de29ec151eb.png)
![图片](https://user-images.githubusercontent.com/76234281/181417835-fccd57f9-c06e-401f-8d30-570959e04343.png)

**Comment by SSmallMonster** [comment]
@FloatXD It looks like missing ns field when search a namespacd resource, may be caused by different version of kubenetes,.
