### ISSUE TITLE
Performing migrate after volume convert will result in missing source nodes on the UI

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#933]
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/f3bed7ed-d01e-4c1a-b681-028a0699eb75)
```
# kubectl get lvr
NAME                                              CAPACITY     NODE        STATE   SYNCED   DEVICE                                                                  AGE
pvc-adda93e6-1c86-4bee-beb7-84f4b1faa94d-fdd8hw   1073741824   k8s-node2   Ready   true     /dev/LocalStorage_PoolHDD-HA/pvc-adda93e6-1c86-4bee-beb7-84f4b1faa94d   21m
pvc-adda93e6-1c86-4bee-beb7-84f4b1faa94d-l4wl2t   1073741824   k8s-node1   Ready   true     /dev/LocalStorage_PoolHDD-HA/pvc-adda93e6-1c86-4bee-beb7-84f4b1faa94d   18m
```

**Comment by Vacant2333** [comment]
after convert action, the localVolumeGroup.spec.accessibility will not be update, there is only 1 node, it should be 2 nodes
<img width="589" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19872346/f30157ca-7923-4b8a-a86e-eb708324ac48">

**Comment by Vacant2333** [comment]
if i create a ha volume, accessibility.nodes will have 2 nodes, but after convert the volume, its still 1 node, looks like convert action didnt update it
<img width="587" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19872346/192fc9ed-5c29-4afb-a1e2-580fa91d4e4d">

**Comment by Vacant2333** [comment]
after convert action, the localVolume.spec.accessibility need update too
<img width="656" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19872346/ee45f977-2e6a-4216-b1ba-c40456278c8f">
