### ISSUE TITLE
hwameistor-local-storage is displayed as Running, but the status of local-storage-csi-controller is actually CrashLoopBackOff

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#934]
hwameistor-local-storage is displayed as Running, but the status of local-storage-csi-controller is actually CrashLoopBackOff
The expectation is:Running should only be displayed when both hwameistor-local-storage and local-storage-csi-controller are normal.
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/5e78af98-782a-40dc-b169-bc7f5719ed2f)
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/fe157f2a-befd-48a3-9817-7ad6e413741a)
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/283bf9ca-3c3d-4c5d-8ea2-9d1a98984101)

**Comment by Vacant2333** [comment]
assign to me
