### ISSUE TITLE
hwameistor-local-disk-manager is displayed as Running, but the status of local-disk-csi-controller is actually CrashLoopBackOff

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#935]
hwameistor-local-disk-manager is displayed as Running, but the status of local-disk-csi-controller is actually CrashLoopBackOff
The expectation is:Running should only be displayed when hwameistor-local-disk-manager and local-disk-csi-controller are normal.
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/f0967d02-8919-4877-a1b6-61bdb6714995)
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/4caf114f-3a3e-4207-8bc7-a34e49f82218)

**Comment by Vacant2333** [comment]
<img width="1039" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19872346/c33619c1-d44b-4cb7-864b-28d7d51e530b">
the status is abnormal but it shows normal, looks like its a frontend error
<img width="480" alt="image" src="https://github.com/hwameistor/hwameistor/assets/19872346/3fbc1122-8ae5-4070-a050-54f0b05b4f86">
