### ISSUE TITLE
磁盘预留需求

### ISSUE THREAD

**Issue by a-spit-to-silkworm-circle** [hwameistor/hwameistor#947]
用户不希望hwameistor自动纳管新添加到节点上的磁盘，这一步骤是否支持手动选择然后确认？

**Comment by SSmallMonster** [comment]
@zhaosimon Disks that don't want to be used by hwameistor can reserved by update spec.reserved `true` in the `LocalDisk` Object.

After doing that, hwameistor won't allocate this disk later.
