### ISSUE TITLE
Can pods with HA  pv migrate to other nodes  successfully when the  primary replicas node is down ?

### ISSUE THREAD

**Issue by qiupingdai** [hwameistor/hwameistor#950]
Can pods with HA  pv migrate to other nodes  successfully when the  primary replicas node is down ?

**Comment by qiupingdai** [comment]
the pods will start after 6 minutes on the node where the secondary replicas runs

**Comment by SSmallMonster** [comment]
Yes.

**Comment by qiupingdai** [comment]
DCE 4.0 DLocal sometimes can not migrate successfully ,  hwameistor should test to double confirm

**Comment by sun7927** [comment]
I am still doubting on it, especially for statefulset. Need a comprehensive test for it.
