### ISSUE TITLE
How hwameistor specify raw disk data volume?

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#965]
I'm a beginner of hwameistor. And I've read all hwameistor docs, but I'm still pretty confused about how I specify a block device as a raw disk data volume.

For example, my k8s cluster as shown below:

```
root@pw1:~/hwameistor# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+rke2r1", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:43Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+rke2r1", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:43Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

root@pw1:~/hwameistor# kubectl get node
NAME   STATUS   ROLES                                    AGE   VERSION
pw1    Ready    control-plane,controlplane,etcd,master   15d   v1.22.6+rke2r1
pw2    Ready    control-plane,controlplane,etcd,master   15d   v1.22.6+rke2r1
pw3    Ready    control-plane,controlplane,etcd,master   15d   v1.22.6+rke2r1
```

Here are my localdisknodes:

```
root@pw1:~/hwameistor# kubectl get localdisknodes.hwameistor.io 
NAME   FREECAPACITY   TOTALCAPACITY   TOTALDISK   STATUS   AGE
pw3                                               Ready    103m
```

Here are my localdisks:

```
root@pw1:~/hwameistor# kubectl get localdisks -o wide
NAME      NODEMATCH   OWNER           PHASE   HEALTH   RESERVED
pw3-sda   pw3         system          Bound   Passed   true
pw3-sdb   pw3         local-storage   Bound   Passed   
pw3-sdc   pw3         system          Bound   Passed   true
pw3-sdd   pw3         system          Bound   Passed   true
pw3-sde   pw3         local-storage   Bound   Passed   
```

Here are my localstoragenode:

```
root@pw1:~/hwameistor# kubectl get localstoragenode -o yaml
apiVersion: v1
items:
- apiVersion: hwameistor.io/v1alpha1
  kind: LocalStorageNode
  metadata:
    creationTimestamp: "2023-07-06T08:18:51Z"
    generation: 1
    name: pw3
    resourceVersion: "13231673"
    uid: 1efcfe23-f723-463a-9b1f-5aebd6d41d36
  spec:
    hostname: pw3
    storageIP: 10.57.132.15
    topogoly:
      region: default
      zone: default
  status:
    conditions:
    - lastTransitionTime: "2023-07-06T08:57:58Z"
      lastUpdateTime: "2023-07-06T08:57:58Z"
      message: Successfully to expand storage capacity
      reason: StorageExpandSuccess
      status: "True"
      type: ExpandSuccess
    poolExtendRecords:
      LocalStorage_PoolHDD:
      - description:
          diskType: HDD
        diskRefs:
        - apiVersion: hwameistor.io/v1alpha1
          kind: LocalDisk
          name: pw3-sdb
          resourceVersion: "13206270"
          uid: cc8c83ca-d95a-4ace-ab8b-d42dac468ee8
        nodeName: pw3
        owner: local-storage
      - description:
          diskType: HDD
        diskRefs:
        - apiVersion: hwameistor.io/v1alpha1
          kind: LocalDisk
          name: pw3-sde
          resourceVersion: "13231652"
          uid: 4fe24da2-3c4b-4d03-a39d-fbdfaa20416e
        nodeName: pw3
        owner: local-storage
    pools:
      LocalStorage_PoolHDD:
        class: HDD
        disks:
        - capacityBytes: 536866717696
          devPath: /dev/sdb
          state: InUse
          type: HDD
        - capacityBytes: 107369988096
          devPath: /dev/sde
          state: InUse
          type: HDD
        freeCapacityBytes: 644236705792
        freeVolumeCount: 1000
        name: LocalStorage_PoolHDD
        totalCapacityBytes: 644236705792
        totalVolumeCount: 1000
        type: REGULAR
        usedCapacityBytes: 0
        usedVolumeCount: 0
        volumeCapacityBytesLimit: 644236705792
    state: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

*Question 1: I want to know whether it is correct that localdisknodes only show node pw3? (my other nodes such as pw1, pw2 only own root disk /dev/sda)*
*Question 2: Why pw3 FREECAPACITY、TOTALCAPACITY、TOTALDISK are empty?*
*Question 3: It seems like hwameistor always select my block device to extend lvm pool, so my node pw3 /dev/sdb、/dev/sde are managed by lvm. But how I specify node pw3 /dev/sdb、/dev/sde as raw disk data volume like this [doc](https://hwameistor.io/docs/volumes_and_nodes/create_hwameistor_volumes/disk_volumes)?*

**Comment by SSmallMonster** [comment]
@AmazingPangWei Thanks for your feedback.

>Question 1: I want to know whether it is correct that localdisknodes only show node pw3? (my other nodes such as pw1, pw2 only own root disk /dev/sda)

**A1:** All pw1,pw2 nodes (related to ds/localdiskmanager) should be displayed. If a problem is displayed, check whether the hwameistor-local-disk-manager-xxxx POD has error logs on the corresponding node.

>Question 2: Why pw3 FREECAPACITY、TOTALCAPACITY、TOTALDISK are empty?

**A2:** From the information provided, there is no disk allocated to the localdisknode resource. By specifying **.spec.owner for the localdiskclaim** resource and **.spec.owner for the localdisk** resource, respectively.

You can view [Disk Storage Node](https://hwameistor.io/docs/volumes_and_nodes/node_expansion/disk_nodes) to expand the disk storage pool.

>Question 3: It seems like hwameistor always select my block device to extend lvm pool, so my node pw3 /dev/sdb、/dev/sde are managed by lvm. But how I specify node pw3 /dev/sdb、/dev/sde as raw disk data volume like this [doc](https://hwameistor.io/docs/volumes_and_nodes/create_hwameistor_volumes/disk_volumes)?

**A3:** Yes, raw disk can be provisioned directly to application.

**Comment by AmazingPangWei** [comment]
@SSmallMonster Thanks for your reply. 

> A1: All pw1,pw2 nodes (related to ds/localdiskmanager) should be displayed. If a problem is displayed, check whether the hwameistor-local-disk-manager-xxxx POD has error logs on the corresponding node.
> A2: From the information provided, there is no disk allocated to the localdisknode resource. By specifying .spec.owner for the localdiskclaim resource and .spec.owner for the localdisk resource, respectively.
> You can view [Disk Storage Node](https://hwameistor.io/docs/volumes_and_nodes/node_expansion/disk_nodes) to expand the disk storage pool.

After checking my cluster, pw1 and pw2 were added taints by my workmate.  All localdisknodes show successfully after removing taints. Besides, I add a disk to pw2 and put it to LocalDiskNode by following your  suggestion, and now localdisknodes as follows:

```
NAME   FREECAPACITY   TOTALCAPACITY   TOTALDISK   STATUS   AGE
pw1                                               Ready    71m
pw2                   214748364800    1           Ready    73m
pw3                                               Ready    3d18h
```

But I'm still confused to Question 3. After I install hwameistor, /dev/sdb、/dev/sde in pw3 has been managed by lvm automatically. Here are my questions: 

1. what is the strategy of hwameistor to choose disk/lvm storage? Why /dev/sdb、/dev/sde are lvm storage? Can I specify it when or after I install hwameistor?
2. Is it possible to turn lvm storage to disk storage? 
3. Is it possible to coexist between lvm storage and disk storage in one node?

I would greatly appreciate it if you could answer these questions.

**Comment by SSmallMonster** [comment]
>1. what is the strategy of hwameistor to choose disk/lvm storage? Why /dev/sdb、/dev/sde are lvm storage? Can I specify it when or after I install hwameistor?

**A1:** By default, when the `owner` of `LocalDiskClaim` is `local-storage`, the empty disks(with no partition and no filesystem on it) will be used for lvm storage. 

If you want specify it after installing hwameistor, there are 2 options as below:

* Remove empty disks on the host before installation.(may be suitable on virtual machine)
* Reserve the disks you want use later manually.

>2. Is it possible to turn lvm storage to disk storage?

**A2:** For disks, the answer is `No`. 

>3. Is it possible to coexist between lvm storage and disk storage in one node?

**A3:** Sure. We support lvm storage and disk storage at the same time.

@AmazingPangWei If you have any other questions, feel free to talk.

**Comment by SSmallMonster** [comment]
The method to reserve disk manually as bellow:
```shell
$ kubectl edit ld <local_disk_name>
apiVersion: hwameistor.io/v1alpha1
kind: LocalDisk
spec:
  capacity: 10485760
-reserved: false
+reserved: true
```

After doing that, this empty disk won't be assigned to an incoming `LocalDiskClaim`.

**Comment by AmazingPangWei** [comment]
I install hwameistor by following [install docs](https://hwameistor.io/cn/docs/quick_start/install/operator) as below:

```
helm repo add hwameistor-operator https://hwameistor.io/hwameistor-operator
helm repo update hwameistor-operator

helm install hwameistor-operator hwameistor-operator/hwameistor-operator -n hwameistor --create-namespace \
--set global.hwameistorImageRegistry=ghcr.m.daocloud.io \
--set global.k8sImageRegistry=m.daocloud.io/registry.k8s.io
```

But according to this install docs as below:

> Operator will claim disk automatically while installing, the available disks will be added into pool of LocalStorageNode.

After I execute these commands, my disks will be claimed by hwameistor-operator (lvm storage by default) automatically. When and how should I edit ld in order to reserve disk manually?

**Comment by SSmallMonster** [comment]
@AmazingPangWei You can reserve disks before `helm install ...`.

In addition, the disk reserve function by hwameistor-operator will be published at next operator version~

**Comment by AmazingPangWei** [comment]
> @AmazingPangWei You can reserve disks before helm install ....

Sorry, I don't understand. There are no LocalDisk crd and object in k8s cluster before `helm install ....`.  How I reserve disks?

> If it is convenient, can you describe the scenarios in which you use hwameistor? This will help us to better improve our function

Well, I'm looking for a local storage system to support [kubevirt](https://kubevirt.io/), which can support vm use local disk. And I think hwameistor matches perfectly, so I wanna go deeper with it.

**Comment by SSmallMonster** [comment]
@AmazingPangWei Sorry, I may have misdescribed it. Currently, disk reservation is implemented in the back-end storage system, but hwameistor-operator has not yet exposed this interface.

**Comment by AmazingPangWei** [comment]
That's OK. Is there another way to work around this case now? Or, when the next operator version is published?

**Comment by SSmallMonster** [comment]
> That's OK. Is there another way to work around this case now? Or, when the next operator version is published?

@buffalo1024 cc, please have a look~

**Comment by sun7927** [comment]
@AmazingPangWei does kubevirt need raw disk volume or disk volume? They are different. My understanding is raw disk volume which can be LVM volume or others but should be sent into the pod as a block device (no filesystem on it).

**Comment by buffalo1024** [comment]
There is a way at this moment.Pull down the operator helm chart and find the hwameistor-cluster cr in the templates and add configs like this 
![image](https://github.com/hwameistor/hwameistor/assets/49835372/90910470-478c-4ce6-ada0-64fb6dbd9735)

**Comment by buffalo1024** [comment]
> 
There is a way at this moment.Pull down the operator helm chart and find the hwameistor-cluster cr in the templates and add configs like this
![image](https://github.com/hwameistor/hwameistor/assets/49835372/ab93db66-79b9-4333-91da-676206cb10d8)

**Comment by buffalo1024** [comment]
> > That's OK. Is there another way to work around this case now? Or, when the next operator version is published?
> 
> @buffalo1024 cc, please have a look~
There is a way at this moment.Pull down the operator helm chart and find the hwameistor-cluster cr in the templates and add configs like this
![](https://user-images.githubusercontent.com/49835372/252268109-ab93db66-79b9-4333-91da-676206cb10d8.png)

**Comment by buffalo1024** [comment]
> That's OK. Is there another way to work around this case now? Or, when the next operator version is published?


There is a way at this moment.Pull down the operator helm chart and find the hwameistor-cluster cr in the templates and add configs like this
![](https://user-images.githubusercontent.com/49835372/252268109-ab93db66-79b9-4333-91da-676206cb10d8.png)

**Comment by AmazingPangWei** [comment]
@buffalo1024 Thank you so much. I'll try this manner.

**Comment by AmazingPangWei** [comment]
@sun7927 In my scenario, whole raw block device and LVM volume are both needed. In other words, a vm can use a whole raw block device to get a better performance, or a vm can use a normal LVM volume for a ordinary use case. 

Hwameistor is able to manage them both, which is fine for me.

**Comment by sun7927** [comment]
> @sun7927 In my scenario, whole raw block device and LVM volume are both needed. In other words, a vm can use a whole raw block device to get a better performance, or a vm can use a normal LVM volume for a ordinary use case.
> 
> Hwameistor is able to manage them both, which is fine for me.
> 
> > They are different. My understanding is raw block volume which can be LVM volume or others but should be sent into the pod as a block device (no filesystem on it).
> 
> You are right. My vm pods use exactly block device.

Got it. For your case, both LVM and disk volumes are required to support kubevirt for different purposes. Same as your understanding, HwameiStor manages both volume types, and each has the special features. You can deep into the details from [official docs](https://hwameistor.io/docs/intro). 

You can list your requirements on the storage (HwameiStor) if you like, we will try best to work out the best solutions with you.

**Comment by AmazingPangWei** [comment]
@sun7927 Thank you for your kindness. Here is my another requirement:

DiskReserveConfigurations in cluster spec are pretty tricky if I want to reserve most disks for raw disk storage, because I have to specify most disks in most nodes one by one. So can operator just stop claiming disk automatically while installing?

**Comment by SSmallMonster** [comment]
@AmazingPangWei Thank you for your patient feedback.

>DiskReserveConfigurations in cluster spec are pretty tricky if I want to reserve most disks for raw disk storage, because I have to specify most disks in most nodes one by one. So can operator just stop claiming disk automatically while installing?

Sure, although the one of initial purposes of the Operator design was to make Day1's operation simpler, I still believe that your requirement is reasonable. We should control the behavior of automatically claiming disks, leaving more operating space for managers and compatible with more scenarios.

>I can't get block device path(DEVLINKS in udevadm) from Localdisk, although it's very easy to get for hwameistor.

Sure, we can add this attribute `DEVLINKS` . Can you describe why this attribute is needed and in what scenarios cannot `devname` or `devpath` be satisfied?  Thanks!!

**Comment by sun7927** [comment]
> @sun7927 Thank you for your kindness. Here are my another requirements:
> 
> 1.DiskReserveConfigurations in cluster spec are pretty tricky if I want to reserve most disks for raw disk storage, because I have to specify most disks in most nodes one by one. So can operator just stop claiming disk automatically while installing?

We are still thinking about the better way for user to configure the disk. This could be one of cases.


> 
> In this way, user like me could batch specifying(e.g. using bash scripts) lvm/disk storage localdiskclaim base on localdisk attributes like capacity, nodeName, disk protocol, etc.
> 
> 2.Localdisk is a very good crd. What I need to do is getting localdisk from control layer, and I can know all disks info. But currently localDisk exposes few attributes, which is not enough in some certain scenarios.
> 
> For example, I need to input block device path when I install rook:
> 
> ```
> storage:
>   nodes:
>   - devices:
>     - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-ua-datadisk-0
>     name: pw1
>   - devices:
>     - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-ua-datadisk-0
>     name: pw3
>   - devices:
>     - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-ua-datadisk-0
>     name: pw2
> ```
> 
> I can't get block device path(DEVLINKS in udevadm) from Localdisk, although it's very easy to get for hwameistor.

Currently, HwameiStor manages the real local disk only. The external volume disk as above should be attached from an external SAN storage system, which are not managed by HwameiStor. If this is your case, we can have a further discussion on it.

**Comment by AmazingPangWei** [comment]
> Can you describe why this attribute is needed and in what scenarios cannot `devname` or `devpath` be satisfied? Thanks!!

Well, `devname` or `devpath` are not immutable actually. For example, say I have a disk, and its device name is /dev/sdc. But device name may be changed to /dev/sdb after reboot, which may make some trouble. A good way to solve it is using `DEVLINKS`, because it's stable. So some applications which use block device directly(e.g. rook) often specify device by `/dev/disk/by-id/xxx`.

By the way, can hwameistor handles the condition that device name changes after reboot?

**Comment by AmazingPangWei** [comment]
> Currently, HwameiStor manages the real local disk only. The external volume disk as above should be attached from an external SAN storage system, which are not managed by HwameiStor. If this is your case, we can have a further discussion on it.

Maybe we could have a further discussion on the [Slack](https://cloud-native.slack.com/messages/hwameistor)

**Comment by sun7927** [comment]
> > Can you describe why this attribute is needed and in what scenarios cannot `devname` or `devpath` be satisfied? Thanks!!
> 
> Well, `devname` or `devpath` are not immutable actually. For example, say I have a disk, and its device name is /dev/sdc. But device name may be changed to /dev/sdb after reboot, which may make some trouble. A good way to solve it is using `DEVLINKS`, because it's stable. So some applications which use block device directly(e.g. rook) often specify device by `/dev/disk/by-id/xxx`.
> 
> By the way, can hwameistor handles the condition that device name changes after reboot?

hwameistor identifies the disk by it's serial number which is unique and stable, and is able to handle name change

**Comment by AmazingPangWei** [comment]
I've distributed our discussion to #982 #983 #984. Thank you all for your kindness.
