### ISSUE TITLE
Do not claim disk automatically while installing

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#983]
DiskReserveConfigurations in cluster spec are pretty tricky if I want to reserve most disks for raw disk storage, because I have to specify most disks in most nodes one by one like this:

![](https://user-images.githubusercontent.com/49835372/252268109-ab93db66-79b9-4333-91da-676206cb10d8.png)

So, can hwameistor-operator just stop claiming disk automatically while installing? As as a administrator,  I need more operating space, which means I can do more detailed designs after hwameistor installation.

**Comment by SSmallMonster** [comment]
@buffalo1024 cc

**Comment by hellokg21** [comment]
Design a new flag such as notClaimDiskAutomatically=true can support it.Or modify codes of the operator to not claim disks defaultly can also solve the problem,and we can design a new flag such as claimDiskAutomatically=true if it is needed.
I dont know which one is better.

**Comment by AmazingPangWei** [comment]
Both flags are worked for me. Maybe you can make your own decisions based on your design.

**Comment by buffalo1024** [comment]
done
