### ISSUE TITLE
NVMe disk cannot be detected correctly

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#989]
Currently(v0.11.1), NVMe disk cannot be detected as below:

https://github.com/hwameistor/hwameistor/blob/64c42e48c1b2a5b78eb4df1dbe7b7bae1810f3d9/pkg/local-disk-manager/utils/sys/devices.go#L189

Localdisk spec.diskAttributes.type only can be DriveTypeHDD or DriveTypeSSD, which does not match the description in the [document](https://hwameistor.io/docs/architecture/modules/ldm):

>At present, LDC supports the following options to describe disk:
>
>* NodeName
>* Capacity
>* DiskType (such as HDD/SSD/**NVMe**) 

To correct it, I have to edit  spec.diskAttributes.type to 'NVMe' manually.

**Comment by zhaosimon** [comment]
this is a known bug, will plan to fix

**Comment by SSmallMonster** [comment]
already supported at https://github.com/hwameistor/hwameistor/pull/1160
